fileExamples = [
    ["1001.Spikes.rar", "1001 Spikes"],
    ["Argus.Panoptes.rar", "Argus Panoptes"],
    ["Art.of.rally.v1.3.1a.rar", "Art of rally"],
    ["ASTRONEER.v1.21.127.0.rar", "ASTRONEER"],
    ["Axiom.Verge.2.v1.0.20.rar", "Axiom Verge 2"],
    ["Beat.Blast.rar", "Beat Blast"],
    ["Before.We.Leave.v1.0301.rar", "Before We Leave"],
    ["Death.Trash.v0.7.14.rar", "Death Trash"],
    ["Delphyq.Early.Access.rar", "Delphyq"],
    ["Diner.Bros.Inc-DARKZER0.rar", "Diner Bros Inc"],
    ["Dorfromantik.v0.2.0.2.rar", "Dorfromantik"],
    ["ENDER.LILIES.Quietus.of.the.Knights.v1.1.2.rar", "ENDER LILIES Quietus of the Knights"],
    ["EVERSPACE.2.Zharkov.The.Vortex.Early.Access.zip", "EVERSPACE 2 Zharkov The Vortex"],
    ["Fallen.Enchantress.Legendary.Heroes.v3.0.rar", "Fallen Enchantress Legendary Heroes"],
    ["Flynn.Son.of.Crimson-GOG.rar", "Flynn Son of Crimson"],
    ["GAME.exe.rar", "GAME"],
    ["Going.Medieval.v0.5.31.15.rar", "Going Medieval"],
    ["GTTOD.Get.To.The.Orange.Door.rar", "GTTOD Get To The Orange Door"],
    ["Hardspace.Shipbreaker.v0.6.0.rar", "Hardspace Shipbreaker"],
    ["Heros.Hour.v1.5.8.rar", "Heros Hour"],
    ["Jazzpunk.Directors.Cut.tar.zst", "Jazzpunk Directors Cut tar"],
    ["LASER.CHESS.Deflection.rar", "LASER CHESS Deflection"],
    ["Minoria.v1.085c.rar", "Minoria"],
    ["Mount.and.Blade.II.Bannerlord.e1.6.1.Hotfix.zip", "Mount and Blade II Bannerlord"],
    ["My.Time.At.Portia.v11.09.2021.zip", "My Time At Portia"],
    ["No.Place.Like.Home.v0.17.134.rar", "No Place Like Home"],
    ["Old.World.v1.0.5463.rar", "Old World"],
    ["Olija.v2.1.2021.rar", "Olija"],
    ["Opus.Magnum.v29.08.2021.rar", "Opus Magnum"],
    ["Oxygen.Not.Included.v479045.rar", "Oxygen Not Included"],
    ["Patron.v1.009.2.rar", "Patron"],
    ["Phasmophobia.v0.3.0.5.zip", "Phasmophobia"],
    ["Planet.Centauri.v0.12.1b.rar", "Planet Centauri"],
    ["Poly.Bridge.2.v1.29.rar", "Poly Bridge 2"],
    ["Power.of.Ten.Build 7121697.rar", "Power of Ten"],
    ["PSYCRON.rar", "PSYCRON"],
    ["Rebel.Inc.Escalation.v0.11.0.6.rar", "Rebel Inc Escalation"],
    ["Residual.rar", "Residual"],
    ["Residual.v1.1.2.rar", "Residual"],
    ["Revita.v0.7.1f.rar", "Revita"],
    ["REVO.rar", "REVO"],
    ["Star.Dynasties.v1.0.0.4.rar", "Star Dynasties"],
    ["Starmancer.v0.1.45.rar", "Starmancer"],
    ["Subnautica.Below.Zero.v45588.zip", "Subnautica Below Zero"],
    ["Subnautica.v68382.rar", "Subnautica"],
    ["Suit.for.Hire.v06.09.2021.rar", "Suit for Hire"],
    ["T.Minus.30.rar", "T Minus"],
    ["Voidtrain.v6849.zip", "Voidtrain"],
    ["Hell.is.Other.Demons.Build.6901054.rar", "Hell is Other Demons"],
    ["ICBM.v1.01.00.rar", "ICBM"],
    ["Infinifactory.v1.0a-GOG.rar", "Infinifactory"],
    ["Legend.of.Keepers.Career.of.a.Dungeon Manager.v1.0.5.rar", "Legend of Keepers Career of a Dungeon Manager"],
    ["Loopindex.rar", "Loopindex"],
    ["Megaquarium.v2.2.4g.rar", "Megaquarium"],
    ["Mindustry.Build.126.2.rar", "Mindustry 2"],
    ["MOLEK.SYNTEZ.v1.13.rar", "MOLEK SYNTEZ"],
    ["Niche.A.Genetics.Survival.Game.v25.06.2021.rar", "Niche A Genetics Survival Game"],
    ["NITE.Team.4.v23.06.2021.rar", "NITE Team 4"],
    ["Noita.v12.03.2021.rar", "Noita"],
    ["Nova.Drift.Build.6568309.rar", "Nova Drift"],
    ["Nuclear.Throne.v06.11.2017.rar", "Nuclear Throne"],
    ["Outer.Wilds.v1.0.7.rar", "Outer Wilds"],
    ["OUTRIDERS-0xdeadc0de (Inc. ONLINE-FIX) RePack [FULL GAME].iso", "OUTRIDERS"],
    ["Parkitect.v1.7t3.rar", "Parkitect"],
    ["POSTAL.4.No.Regerts.Thursday.Early.Access.zip", "POSTAL 4 No Regerts Thursday"], # XXX NOTE that this one still isn't right - but I don't want to start stripping off weekdays from everything so it stays
    ["Prison.Architect.v19.06.2021.rar", "Prison Architect"],
    ["Rail.Route.Early.Access.rar", "Rail Route"],
    ["Rain.On.Your.Parade.rar", "Rain On Your Parade"],
    ["Rogue.Heroes.Ruins.of.Tasos.v2.0.rar", "Rogue Heroes Ruins of Tasos"],
    ["Rogue.Legacy.2.v29.06.2021.rar", "Rogue Legacy 2"],
    ["ROUNDS.rar", "ROUNDS"],
    ["Serin.Fate.v0.5.4.9.rar", "Serin Fate"],
    ["Space.Haven.v0.12.6.rar", "Space Haven"],
    ["SpaceChem.v1015.rar", "SpaceChem"],
    ["SPROUT.Build.6632648.rar", "SPROUT"],
    ["Star.Renegades.v1.4.0.5.rar", "Star Renegades"],
    ["StarDrive.2.v1.5h.rar", "StarDrive 2"],
    ["Startup.Company.v1.24.rar", "Startup Company"],
    ["Struggling.v1.0.4.rar", "Struggling"],
    ["Sunblaze.v21.06.2021.rar", "Sunblaze"],
    ["Surviving.the.Aftermath.v1.16.0.9362.rar", "Surviving the Aftermath"],
    ["The.Citadel.v22.06.2021.rar", "The Citadel"],
    ["The.Slormancer.v0.2.03.rar", "The Slormancer"],
    ["The.Unexpected.Quest.rar", "The Unexpected Quest"],
    ["Wayward.Beta.2.10.7.rar", "Wayward Beta"],
    ["Zoo.Tycoon.2.Ultimate.Collection.zip", "Zoo Tycoon 2 Ultimate Collection"],
    ["ELDERBORN.v1.037.rar", "ELDERBORN"],
    ["GRIME.v1.0.4.5.rar", "GRIME"],
    ["HighFleet.v11.08.2021.rar", "HighFleet"],
    ["INVERT.rar", "INVERT"],
    ["Spelunky.2.v1.23.2.rar", "Spelunky 2"],
    ["Stationeers.v0.2.2943.14662.rar", "Stationeers"],
    ["Straimium.Immortaly.Build.6304372.rar", "Straimium Immortaly"],
    ["Terraforming.Mars.v1.3000.rar", "Terraforming Mars"],
    ["TerraTech.v1.4.10.3.rar", "TerraTech"],
    ["The.Last.Spell.v0.92.2.3.rar", "The Last Spell"],
    ["Voxel.Tycoon.v0.86.1.rar", "Voxel Tycoon"],
    ["Warpips.v1.4.rar", "Warpips"],
    ["Wildermyth.v1.0.325.rar", "Wildermyth"],
    ["Wire.Lips.v1.11.rar", "Wire Lips"],
    ["Wirewalk.rar", "Wirewalk"],
    ["30XX.v0.21.2.rar", "30XX"],
    ["5D.Chess.With.Multiverse.Time.Travel.v28.10.2020.rar", "5D Chess With Multiverse Time Travel"],
    ["8Doors.Arums.Afterlife.Adventure.Build.6891335.rar", "8Doors Arums Afterlife Adventure"],
    ["A.Little.Golf.Journey.v0.0.115.rar", "A Little Golf Journey"],
    ["A.Monsters.Expedition.v09.08.2021.rar", "A Monsters Expedition"],
    ["A.Short.Hike.v1.9.3.rar", "A Short Hike"],
    ["A.Tale.of.Synapse.The.Chaos.Theories.v23.07.2021.rar", "A Tale of Synapse The Chaos Theories"],
    ["Age.of.Darkness.Final.Stand.v0.1.5.rar", "Age of Darkness Final Stand"],
    ["AI.War.2.v3.307.rar", "AI War 2"],
    ["Airborne.Kingdom.v1.0.1.rar", "Airborne Kingdom"],
    ["Airmen.v18.07.2021.rar", "Airmen"],
    ["Airships.Conquer.the.Skies.v1.0.21.4.rar", "Airships Conquer the Skies"],
    ["Astrox.Imperium.v0.0121.rar", "Astrox Imperium"],
    ["Atrio.The.Dark.Wild.rar", "Atrio The Dark Wild"],
    ["Avorion.v2.0.6.rar", "Avorion"],
    ["Axiom.Verge.v1.41.rar", "Axiom Verge"],
    ["Baba.Is.You.rar", "Baba Is You"],
    ["Banished.v1.0.7.Build.170910.rar", "Banished"],
    ["Bastion.v1.50436.rar", "Bastion"],
    ["Batbarian.Testament.of.the.Primordials.v1.2.1.rar", "Batbarian Testament of the Primordials"],
    ["Beard.Blade.rar", "Beard Blade"],
    ["Beat.Hazard.2.v1.16.rar", "Beat Hazard 2"],
    ["Bloons.TD.6.v27.0.4218.rar", "Bloons TD 6"],
    ["Breakwaters.v0.1.59.rar", "Breakwaters"],
    ["Brick.Rigs.v16.07.2021.rar", "Brick Rigs"],
    ["Bug.Fables.The.Everlasting.Sapling.v1.1.rar", "Bug Fables The Everlasting Sapling"],
    ["Carcassonne.Tiles.&.Tactics.v1.10.2967.2.rar", "Carcassonne Tiles & Tactics"],
    ["Carrier.Command.2.rar", "Carrier Command 2"],
    ["Cartel.Tycoon.v0.9.0.1660.rar", "Cartel Tycoon"],
    ["Castlevania.Advance.Collection.rar", "Castlevania Advance Collection"],
    ["Caves.of.Qud.v2.0.202.97.rar", "Caves of Qud"],
    ["Chernobylite.Final.Stage.Early.Access.rar", "Chernobylite Final Stage"],
    ["Clan.N.v23.07.2021.rar", "Clan N"],
    ["Colony.Survival.v0.8.1.8.rar", "Colony Survival"],
    ["Craftopia.v20210715.1741.rar", "Craftopia"],
    ["Crea.v1.7.6.rar", "Crea"],
    ["Crumble.Build.6163855.rar", "Crumble"],
    ["Crusader.Kings.III.v1.4.2.rar", "Crusader Kings III"],
    ["Cyber.Defense.rar", "Cyber Defense"],
    ["Dark.Light.v26.07.2021.rar", "Dark Light"],
    ["Darkest Dungeon 2.rar", "Darkest Dungeon 2"],
    ["Dead.Estate.v1.1.2.rar", "Dead Estate"],
    ["Deaths.Gambit.Afterlife.v1.1.5.FIXED.rar", "Deaths Gambit Afterlife"],
    ["Delver.v1.07.rar", "Delver"],
    ["Despots.Game.v0.15.0.3.rar", "Despots Game"],
    ["Dininho.Adventures.Definitive.Edition.Build.6922959.rar", "Dininho Adventures Definitive Edition"],
    ["Dread.Templar.Early.Access.rar", "Dread Templar"],
    ["Dream.Engines.Nomad.Cities.v0.5.259.rar", "Dream Engines Nomad Cities"],
    ["Dredgers.v44.rar", "Dredgers"],
    ["Duck.Game.v1.5.rar", "Duck Game"],
    ["Dungeon.Keeper.2.rar", "Dungeon Keeper 2"],
    ["Dungeonmans.v1.10f.rar", "Dungeonmans"],
    ["Dungeons.of.Edera.October.Early.Access.rar", "Dungeons of Edera October"],
    ["Dungreed.v13.08.2021.rar", "Dungreed"],
    ["Eastward.v1.1.0b.rar", "Eastward"],
    ["Edge.Of.Galaxy.rar", "Edge Of Galaxy"],
    ["Eggcelerate.rar", "Eggcelerate"],
    ["Embark.v0.810.rar", "Embark"],
    ["Empires.of.the.Undergrowth.v0.23001.rar", "Empires of the Undergrowth"],
    ["Endless.Legend.v1.8.52.rar", "Endless Legend"],
    ["Enter.the.Gungeon.v2.1.9.rar", "Enter the Gungeon"],
    ["Estranged.The.Departure.Build.6786590.rar", "Estranged The Departure"],
    ["Factory.Town.rar", "Factory Town"],
    ["Factory.Town.v1.5.2.rar", "Factory Town"],
    ["Factory.Town.v1.7.3.rar", "Factory Town"],
    ["Fates.of.Ort.v1.3.0.rar", "Fates of Ort"],
    ["Final.Upgrade.v0.2.47.rar", "Final Upgrade"],
    ["Flynn.Son.of.Crimson.v1.1.rar", "Flynn Son of Crimson"],
    ["Forager.v5.0.0.rar", "Forager"],
    ["Force.of.Nature.2.v1.0.21.rar", "Force of Nature 2"],
    ["Fort.Triumph.v1.1.7.rar", "Fort Triumph"],
    ["Foundation.v1.8.0.8.1118.rar", "Foundation"],
    ["Fury.Unleashed.v1.8.2.rar", "Fury Unleashed"],
    ["Future.Tanks.Area.rar", "Future Tanks Area"],
    ["Garfield.Kart.Furious.Racing.tar.zst", "Garfield Kart Furious Racing tar"],
    ["Garlic.rar", "Garlic"],
    ["Gedonia.v0.33b.rar", "Gedonia"],
    ["Get.Packed.Fully.Loaded.rar", "Get Packed Fully Loaded"],
    ["Getting.Over.It.with.Bennett.Foddy.v1.5762.rar", "Getting Over It with Bennett Foddy"],
    ["GolfTopia.v20.07.2021.rar", "GolfTopia"],
    ["GoNNER+2.tar.zst", "GoNNER+2 tar"],
    ["Goop.Loop.rar", "Goop Loop"],
    ["Grow.Song.of.the.Evertree.v03.12.2021.rar", "Grow Song of the Evertree"],
    ["Guild.of.Darksteel.GOG.rar", "Guild of Darksteel GOG"],
    ["Half.Wing.rar", "Half Wing"],
    ["Haunt.Chaser.Early.Access.zip", "Haunt Chaser"],
    ["Hell.Architect.v1.0.18.rar", "Hell Architect"],
    ["HighFleet.v1.14.rar", "HighFleet"],
    ["Hydroneer.v1.7.rar", "Hydroneer"],
    ["Hyrule Warriors Age of Calamity (XCI).7z", "Hyrule Warriors Age of Calamity (XCI)"],
    ["Imagine.Earth.v1.2.3.rar", "Imagine Earth"],
    ["Imagine.Earth.v1.4.2.rar", "Imagine Earth"],
    ["Industries.of.Titan.v0.18.4.rar", "Industries of Titan"],
    ["InfraSpace.v7.3.132.rar", "InfraSpace"],
    ["Interstellar.Space.Genesis.v1.3.4.rar", "Interstellar Space Genesis"],
    ["Intravenous.v1.1.6.rar", "Intravenous"],
    ["Intravenous.v1.2.16.rar", "Intravenous"],
    ["It.Lurks.Below.v1.01.62.rar", "It Lurks Below"],
    ["Kainga.Seeds.of.Civilization.Early.Access.rar", "Kainga Seeds of Civilization"],
    ["Kingdoms.Reborn.v0.54.rar", "Kingdoms Reborn"],
    ["KingSim.rar", "KingSim"],
    ["Kubifaktorium.v24.11.2021.rar", "Kubifaktorium"],
    ["Kubifaktorium.v6.12.2021.rar", "Kubifaktorium"],
    ["Lens.Island.v26.11.2021.rar", "Lens Island"],
    ["Logic.World.v0.90.3.rar", "Logic World"],
    ["Lonely.Mountains.Downhill.v20.07.2021.rar", "Lonely Mountains Downhill"],
    ["Loop.Hero.rar", "Loop Hero"],
    ["Mad.Games.Tycoon.2.v2021.07.22A.rar", "Mad Games Tycoon 2"],
    ["Mashinky.v0.60.181.rar", "Mashinky"],
    ["Master.of.Magic.v1.3.1.rar", "Master of Magic"],
    ["Melvor.Idle.v1.0.rar", "Melvor Idle"],
    ["Mercury.Fallen.v30.4.rar", "Mercury Fallen"],
    ["Milli.and.Greg.rar", "Milli and Greg"],
    ["Mini.Metro.Creative.Mode.rar", "Mini Metro Creative Mode"],
    ["Mini.Metro.Release.49.rar", "Mini Metro Release"],
    ["MMORPG.Tycoon.2.v0.18.0.rar", "MMORPG Tycoon 2"],
    ["MMORPG.Tycoon.2.v0.18.17.rar", "MMORPG Tycoon 2"],
    ["Nebuchadnezzar.v1.2.4.rar", "Nebuchadnezzar"],
    ["Neon.Abyss.v1.4.4.rar", "Neon Abyss"],
    ["Neon.Abyss.v1.4.5.rar", "Neon Abyss"],
    ["Neon.Chrome.v1.1.7.rar", "Neon Chrome"],
    ["Nimbatus.The.Space.Drone.Constructor.v1.1.4.rar", "Nimbatus The Space Drone Constructor"],
    ["NMNE.rar", "NMNE"],
    ["Nuclear.Blaze.v1.0.3.rar", "Nuclear Blaze"],
    ["Old.World.v1.0.56149.rar", "Old World"],
    ["Orbital.Bullet.The.360.Rogue.lite.v0.2.3.rar", "Orbital Bullet The 360 Rogue lite"],
    ["Order.of.Battle.World.War.II.v9.0.3.rar", "Order of Battle World War II"],
    ["Oxenfree.v3.1.0.rar", "Oxenfree"],
    ["People.Playground.v1.22.rar", "People Playground"],
    ["Phantom.Brigade.v0.13.0.rar", "Phantom Brigade"],
    ["PICO.PARK.rar", "PICO PARK"],
    ["Post.Void.v1.1.0b.rar", "Post Void"],
    ["Potion.Craft.Alchemist.Simulator.Early.Access.rar", "Potion Craft Alchemist Simulator"],
    ["Project.Downfall.v0.9.22.0.rar", "Project Downfall"],
    ["Project.Hospital.v1.2.22362.rar", "Project Hospital"],
    ["Project.Warlock.v1.0.4.6.rar", "Project Warlock"],
    ["Quake.II.RTX-GOG.rar", "Quake II RTX"],
    ["Ragnorium.Episode.31.I.Build.My.Colony.Early.Access.rar", "Ragnorium Episode 31 I Build My Colony"],
    ["Ravensword.Undaunted.v0.2.1.HotFix.rar", "Ravensword Undaunted"],
    ["Re.Surs.rar", "Re Surs"],
    ["Realms.of.Magic.v0.22.0.rar", "Realms of Magic"],
    ["Record.of.Lodoss.War.Deedlit.in.Wonder.Labyrinth.v1.1.1.8.rar", "Record of Lodoss War Deedlit in Wonder Labyrinth"],
    ["REPLIKATOR.Early.Access.rar", "REPLIKATOR"],
    ["Rift.Wizard.rar", "Rift Wizard"],
    ["RimWorld.v1.3.3171.rar", "RimWorld"],
    ["Rise.to.Ruins-GOG.zip", "Rise to Ruins"],
    ["Rogues.Tale.v2.11.rar", "Rogues Tale"],
    ["Ruinarch.v0.7.rar", "Ruinarch"],
    ["Samurai.Gunn.2.rar", "Samurai Gunn 2"],
    ["SATORI.rar", "SATORI"],
    ["Seed.of.Life.v1.0.4.rar", "Seed of Life"],
    ["Selfless.Heroes.rar", "Selfless Heroes"],
    ["shapez.io.v1.4.4.rar", "shapez io"],
    ["Siege.Survival.Gloria.Victis.v6998499.zip", "Siege Survival Gloria Victis"],
    ["simmiland.v1.4.15.rar", "simmiland"],
    ["Sir.Lovelot.rar", "Sir Lovelot"],
    ["Skid.Cities.rar", "Skid Cities"],
    ["Slipways.v1.1-777.rar", "Slipways"],
    ["Songs.of.Syx.v0.58.35b.rar", "Songs of Syx"],
    ["Sonic.and.All.Stars.Racing.Transformed.Collection.rar", "Sonic and All Stars Racing Transformed Collection"],
    ["Space.Engineers.v1.199.020.zip", "Space Engineers"],
    ["Star.Valor.v1.3.1.rar", "Star Valor"],
    ["Stardew.Valley.v1.5.4.Hotfix.rar", "Stardew Valley"],
    ["Steel.Assault.Build.7670582.rar", "Steel Assault"],
    ["Stephens.Sausage.Roll.tar.zst", "Stephens Sausage Roll tar"],
    ["Stormworks.Buil.and.Rescue.v1.2.12.rar", "Stormworks Buil and Rescue"],
    ["Superfighters.Deluxe.v1.3.7d.rar", "Superfighters Deluxe"],
    ["Surgeon.Simulator.2.rar", "Surgeon Simulator 2"],
    ["Sword.of.the.Necromancer.v2.1.0.rar", "Sword of the Necromancer"],
    ["Tales.of.Majeyal.v1.7.4.ALL.DLC.GOG.rar", "Tales of Majeyal"],
    ["Teardown.v0.9.0.rar", "Teardown"],
    ["That.Flipping.Mountain.rar", "That Flipping Mountain"],
    ["The Legend of Zelda Skyward Sword HD.nsp", "The Legend of Zelda Skyward Sword HD"],
    ["The.Battle.of.Polytopia.v2.0.58.rar", "The Battle of Polytopia"],
    ["The.Binding.of.Isaac.Repentance.v1.7.7.rar", "The Binding of Isaac Repentance"],
    ["The.Colonists.v1.5.14.2.rar", "The Colonists"],
    ["THE.CORRIDOR.rar", "THE CORRIDOR"],
    ["The.Immortal.Mayor.rar", "The Immortal Mayor"],
    ["The.Riftbreaker.Build.6932326.zip", "The Riftbreaker"],
    ["The.Signal.State.rar", "The Signal State"],
    ["The.Universim.v0.1.51.rar", "The Universim"],
    ["TheoTown.v04.09.2021.rar", "TheoTown"],
    ["TheoTown.v1.10.13.rar", "TheoTown"],
    ["They.Are.Billions.v1.1.13.rar", "They Are Billions"],
    ["Tile.Miner.rar", "Tile Miner"],
    ["Timberborn.v27.09.2021.rar", "Timberborn"],
    ["Timberborn.v30.11.2021.rar", "Timberborn"],
    ["Tinkertown.v0.8.1.rar", "Tinkertown"],
    ["Transport.INC.v1.3.5.rar", "Transport INC"],
    ["Trashed.v0.55.rar", "Trashed"],
    ["Travellers.Rest.v0.4.3.1f.rar", "Travellers Rest"],
    ["TROUBLESHOOTER.Abandoned.Children.v09.08.2021.zip", "TROUBLESHOOTER Abandoned Children"],
    ["Turmoil.v3.0.38a.rar", "Turmoil"],
    ["uFactory.v0.6.5.3.rar", "uFactory"],
    ["Ultimate.ADOM.Caverns.of.Chaos.v1.0.0.2.rar", "Ultimate ADOM Caverns of Chaos"],
    ["ULTRAKILL.Build.6928744.rar", "ULTRAKILL"],
    ["Unbound.Worlds.Apart.v1.0.3.rar", "Unbound Worlds Apart"],
    ["UnderMine.v1.2.1.14.rar", "UnderMine"],
    ["Undungeon.v1.0.5.rar", "Undungeon"],
    ["Universe.Sandbox.2.v27.2.1.rar", "Universe Sandbox 2"],
    ["Universe.Sandbox.2.v28.2.0.rar", "Universe Sandbox 2"],
    ["Unrailed.v25.07.2021.rar", "Unrailed"],
    ["UNSIGHTED.rar", "UNSIGHTED"],
    ["Unsouled.Early.Access.rar", "Unsouled"],
    ["Usurper.Soulbound.Early.Access.rar", "Usurper Soulbound"],
    ["Valheim.v0.204.4.rar", "Valheim"],
    ["Valheim.v0.205.5.rar", "Valheim"],
    ["Vandozer.rar", "Vandozer"],
    ["Voidigo.rar", "Voidigo"],
    ["Volcanoids.v1.25.338.0.rar", "Volcanoids"],
    ["Vomitoreum.v02.08.2021.rar", "Vomitoreum"],
    ["Voxel.Tycoon.v0.87.rar", "Voxel Tycoon"],
    ["VVVVVV.v2.3.3.rar", "VVVVVV"],
    ["Wandersong.rar", "Wandersong"],
    ["Whos.Your.Daddy.v04.09.2021.rar", "Whos Your Daddy"],
    ["Xenias.Ark.v1.0.1.rar", "Xenias Ark"],
    ["Ziggurat.2.v01.12.2021.rar", "Ziggurat 2"],
    ["Anew.The.Distant.Light.Early.Access.rar", "Anew The Distant Light"],
    ["Arietta.of.Spirits.rar", "Arietta of Spirits"],
    ["BAD.END.THEATER.rar", "BAD END THEATER"],
    ["Big.NEON.Tower.VS.Tiny.Square.rar", "Big NEON Tower VS Tiny Square"],
    ["Blaster.Master.Zero.3.rar", "Blaster Master Zero 3"],
    ["Bomb.Chicken.rar", "Bomb Chicken"],
    ["Celeste.v1.4.0.0.rar", "Celeste"],
    ["Cyber.Shadow.v1.04.rar", "Cyber Shadow"],
    ["Drunken.Dad.Simulator.rar", "Drunken Dad Simulator"],
    ["Galactic.Mining.Corp.Build.7148823.rar", "Galactic Mining Corp"],
    ["Glyph.Build.7166458.rar", "Glyph"],
    ["Goats.Tale.Early.Access.rar", "Goats Tale"],
    ["Hundred.Days.Winemaking.Simulator.v1.1.3w1.rar", "Hundred Days Winemaking Simulator"],
    ["Mini.Motorways.v10.08.2021.rar", "Mini Motorways"],
    ["PixARK.v1.134.rar", "PixARK"],
    ["Rise.of.Industry.v2.3.2.rar", "Rise of Industry"],
    ["Rising.Hell.v1.1.4.rar", "Rising Hell"],
    ["SimCasino.v18.06.2021.rar", "SimCasino"],
    ["SNKRX.v26.07.2021.rar", "SNKRX"],
    ["Stand.By.Me.v1.1.3.rar", "Stand By Me"],
    ["Stardew.Valley.v1.5.5.Beta.rar", "Stardew Valley"],
    ["Sunshine.Heavy.Industries.rar", "Sunshine Heavy Industries"],
    ["Super.Chicken.Jumper.rar", "Super Chicken Jumper"],
    ["Super.Worldbox.v0.9.6.rar", "Super Worldbox"],
    ["Train.Valley.2.Build.197.rar", "Train Valley 2"],
    ["Vagante.v1.10.rar", "Vagante"],
    ["Webbed.v1.03b.rar", "Webbed"],
    ["Wizard.of.Legend.Phantom.rar", "Wizard of Legend Phantom"],
    ["60.Parsecs.v1.3.2.rar", "60 Parsecs"],
    ["A.Short.Hike.v1.8.14.rar", "A Short Hike"],
    ["ADOM.Ancient.Domains.Of.Mystery.v3.3.4.1.rar", "ADOM Ancient Domains Of Mystery"],
    ["Almighty.Kill.Your.Gods.Early.Access.zip", "Almighty Kill Your Gods"],
    ["Amnesia.The.Dark.Descent.v02.10.2018.rar", "Amnesia The Dark Descent"],
    ["Another.Brick.in.the.Mall.v1.1.4.rar", "Another Brick in the Mall"],
    ["Ape.Out.rar", "Ape Out"],
    ["Astalon.Tears.of.the.Earth.v1.0.11.rar", "Astalon Tears of the Earth"],
    ["Autonauts.v137.14.11.rar", "Autonauts"],
    ["Bamerang.rar", "Bamerang"],
    ["Barotrauma.Thunder.Under.The.Ice.Early.Access.rar", "Barotrauma Thunder Under The Ice"],
    ["Battle.Axe.rar", "Battle Axe"],
    ["BlackChain.v1.0.7.rar", "BlackChain"],
    ["Blaster.Master.Zero.2.v16.06.2021.rar", "Blaster Master Zero 2"],
    ["Blaster.Master.Zero.v16.06.2021.rar", "Blaster Master Zero"],
    ["Boppio.v0.3.0.rar", "Boppio"],
    ["Broken.Universe.Tower.Defense.Early.Access.rar", "Broken Universe Tower Defense"],
    ["Bugsnax.v1.06.58006.rar", "Bugsnax"],
    ["City.Game.Studio.v1.0.rar", "City Game Studio"],
    ["Cloud.Gardens.v0.13.8.rar", "Cloud Gardens"],
    ["Craft.The.World.v1.9.002.rar", "Craft The World"],
    ["Crosscode.1.4.1-4.GOG.rar", "Crosscode"],
    ["Curse.of.the.Dead.Gods.v1.24.4.rar", "Curse of the Dead Gods"],
    ["Distant.Kingdoms.v11519.rar", "Distant Kingdoms"],
    ["Dobo's.Heroes.rar", "Dobo's Heroes"],
    ["Dragon.Quest.Builders.2.v20210428.rar", "Dragon Quest Builders 2"],
    ["Eador.Masters.of.the.Broken.World.v1.8.3.rar", "Eador Masters of the Broken World"],
    ["Eco.v0.9.3.5.rar", "Eco"],
    ["Empyrion.Galactic.Survival.v1.5.1.zip", "Empyrion Galactic Survival"],
    ["Endzone.A.World.Apart.v1.0.7822.rar", "Endzone A World Apart"],
    ["Environmental.Station.Alpha.v06.02.2020.rar", "Environmental Station Alpha"],
    ["Five.Nations.v1.0.2.rar", "Five Nations"],
    ["Flotsam.v0.4.0e4.rar", "Flotsam"],
    ["FTL.Faster.Than.Light.v1.6.14.rar", "FTL Faster Than Light"],
    ["GemCraft.Frostborn.Wrath.v1.2.1a.rar", "GemCraft Frostborn Wrath"],
    ["Geneforge.1.Mutagen.v1.0.2.1.rar", "Geneforge 1 Mutagen"],
    ["Geometry.Arena.rar", "Geometry Arena"],
    ["GetsuFumaDen.Undying.Moon.v17.06.2021.rar", "GetsuFumaDen Undying Moon"],
    ["Golden.Light.v04.06.2021.rar", "Golden Light"],
    ["Good.Company.v0.9.3.rar", "Good Company"],
    ["Green.With.Energy.rar", "Green With Energy"],
    ["Hades.v1.37996.zip", "Hades"],
    ["Hard.Reset.Redux.v1.1.3.0.zip", "Hard Reset Redux"],
    ["HROT.v0.3.1.rar", "HROT"],
    ["HUNTDOWN.v13.05.2021.rar", "HUNTDOWN"],
    ["Hyper.Light.Drifter.Update.36.rar", "Hyper Light Drifter Update"],
    ["Hyper.Light.Drifter.v17.10.2018.rar", "Hyper Light Drifter"],
    ["Infinitode.2.rar", "Infinitode 2"],
    ["Katana.ZERO.v1.0.5.rar", "Katana ZERO"],
    ["Kenshi.v1.0.55.zip", "Kenshi"],
    ["Kingdoms.and.Castles.v117r7z.rar", "Kingdoms and Castles"],
    ["Last.Epoch.v0.8.Early.Access.zip", "Last Epoch"],
    ["Lets.Build.a.Zoo.rar", "Lets Build a Zoo"],
    ["Lewd.Girls.Leave.Me.Alone.rar", "Lewd Girls Leave Me Alone"],
    ["Lichtspeer.Double.Speer.Edition.v1.01.rar", "Lichtspeer Double Speer Edition"],
    ["Lost.Ruins.v1.0.9.rar", "Lost Ruins"],
    ["Mayhem.in.Single.Valley.v4.0.7.rar", "Mayhem in Single Valley"],
    ["Night.Delivery.v1.09.rar", "Night Delivery"],
    ["Oceans.Heart.rar", "Oceans Heart"],
    ["Orcs.Must.Die.2.Complete.zip", "Orcs Must Die 2 Complete"],
    ["Overcrowd.A.Commute.Em.Up.v1.0.41.rar", "Overcrowd A Commute Em Up"],
    ["Paleon.rar", "Paleon"],
    ["Panzer.Corps.2.Field.Marshal.Edition.v1.01.23.zip", "Panzer Corps 2 Field Marshal Edition"],
    ["Patch.Quest.Early.Access.rar", "Patch Quest"],
    ["Portal.Reloaded.v1.1.0.rar", "Portal Reloaded"],
    ["Prodigal.v1.3.1.rar", "Prodigal"],
    ["Production.Line.v1.81e.rar", "Production Line"],
    ["R.Type.Dimensions.rar", "R Type Dimensions"],
    ["Radical.Relocation.v1.5.0.rar", "Radical Relocation"],
    ["Raft.Update.13.rar", "Raft Update"],
    ["Rain.World.v1.5.rar", "Rain World"],
    ["RECONNECT.The.Heart.of.Darkness.Early.Access.rar", "RECONNECT The Heart of Darkness"],
    ["Resident Evil Village-FULL UNLOCKED RePack.iso", "Resident Evil Village-FULL UNLOCKED RePack"],
    ["Reventure.v1.9.5.rar", "Reventure"],
    ["rld-sanctum2.iso", "sanctum2"], # XXX NOTE this one is also not entirely correct, as there should be a space between sanctum and 2, but I'm not going to go add arbitrary spaces
    ["ScourgeBringer.v1.52.rar", "ScourgeBringer"],
    ["setup_8bit_hordes_2.0.0.3.exe", "8bit hordes"],
    ["Simonas.Requiem.Build.6668649.rar", "Simonas Requiem"],
    ["SimPocalypse.rar", "SimPocalypse"],
    ["Sky.Haven.v0.6.3.39.rar", "Sky Haven"],
    ["Slave.Princess.Sarah.rar", "Slave Princess Sarah"],
    ["Slime.Rancher.v1.4.3.rar", "Slime Rancher"],
    ["Snowtopia.Ski.Resort.Tycoon.v0.14.12.rar", "Snowtopia Ski Resort Tycoon"],
    ["Software.Inc.Alpha.11.7.55.rar", "Software Inc Alpha"],
    ["Speed.Limit.v1.2.3.rar", "Speed Limit"],
    ["Starbound.v1.4.4.rar", "Starbound"],
    ["StarSector.0.9.5a-RC15.rar", "StarSector"],
    ["Stronghold.Crusader.HD.v1.41a.rar", "Stronghold Crusader HD"],
    ["Stronghold2.Steam.Edition.v1.5.zip", "Stronghold2 Steam Edition"],
    ["Super.Bit.Blaster.XL.rar", "Super Bit Blaster XL"],
    ["Tales.of.Majeyal.v1.7.2.ALl.DLC.GOG.rar", "Tales of Majeyal"],
    ["Tangledeep.v1.4i_3.rar", "Tangledeep"],
    ["Teardown.v0.7.2.rar", "Teardown"],
    ["Terraria.v1.4.2.3.rar", "Terraria"],
    ["Tesla.vs.Lovecraft.v1.0.5.rar", "Tesla vs Lovecraft"],
    ["The.Company.Man.v5.06.2021.rar", "The Company Man"],
    ["The.Last.Spell.v0.91.3.rar", "The Last Spell"],
    ["The.Messenger.v04.10.2019.rar", "The Messenger"],
    ["The.Tenants.v0.553.rar", "The Tenants"],
    ["Time.to.Morp.rar", "Time to Morp"],
    ["TWWWR.Build.6228108.rar", "TWWWR"],
    ["Valley.of.No.Roads.rar", "Valley of No Roads"],
    ["Vigil.The.Longest.Night.The.Bounty.of.the.Night.rar", "Vigil The Longest Night The Bounty of the Night"],
    ["Viscerafest.v0.9.0.5.rar", "Viscerafest"],
    ["Why.Pizza.rar", "Why Pizza"],
    ["Within.the.Blade.v1.1.0.1.rar", "Within the Blade"],
    ["Wobbledogs.Early.Access.rar", "Wobbledogs"],
    ["Wobbly.Life.v0.5.5.rar", "Wobbly Life"],
    ["Workers.&.Resources.Soviet.Republic.v0.8.4.21.rar", "Workers & Resources Soviet Republic"],
    ["World.of.Contraptions.v0.34.0.rar", "World of Contraptions"],
    ["Worms.Armageddon.v3.8.1.GOG.rar", "Worms Armageddon"],
]

from RegexPlugin import InputSanitizer
inputSanitizer = InputSanitizer()
# outputDirs = [inputSanitizer.perform_directory_name_replacement(dirName) for dirName in directories]
fileTestCaseData = [[filename, inputSanitizer.perform_filename_replacement(filename), correctTranslation] for filename, correctTranslation in fileExamples]

import unittest
from parameterized import parameterized

class TestSequence(unittest.TestCase):
    @parameterized.expand(fileTestCaseData)
    def test_sequence(self, originalFilename: str, actualTranslation: str, correctTranslation: str):
        self.assertEqual(actualTranslation, correctTranslation, f"expected '{actualTranslation}' to be '{correctTranslation}'. Original Filename: '{originalFilename}'")

if __name__ == '__main__':
    unittest.main()



