dirExamples = [
    ["1001.Spikes", "1001 Spikes"],
    ["Amnesia.Rebirth.v1.4-GOG", "Amnesia Rebirth"],
    ["Citystate II [FitGirl Repack]", "Citystate II"],
    ["Eastward-CODEX", "Eastward"],
    ["Fort.Triumph.v1.1.6-PLAZA", "Fort Triumph"],
    ["Into the Pit - [DODI Repack]", "Into the Pit"],
    ["Limitless.Hunger-DARKSiDERS", "Limitless Hunger"],
    ["Little Nightmares II - EE [FitGirl Repack]", "Little Nightmares II"],
    ["Lumione [FitGirl Repack]", "Lumione"],
    ["Mass_Effect_Legendary_Edition-FLT", "Mass Effect Legendary Edition"],
    [
        "Pathfinder.Wrath.of.the.Righteous.v1.0.3c-GOG",
        "Pathfinder Wrath of the Righteous",
    ],
    ["R-Type Final 2 [FitGirl Repack]", "R-Type Final 2"],
    ["Red.Solstice.2.Survivors.v20210809.REPACK-KaOs", "Red Solstice 2 Survivors"],
    [
        "Rise.And.Fall.Civilizations.At.War.v1.5.(2006).REPACK-KaOs",
        "Rise And Fall Civilizations At War",
    ],
    ["Scrapnaut [FitGirl Repack]", "Scrapnaut"],
    ["Severed Steel [FitGirl Repack]", "Severed Steel"],
    ["SkateBIRD [FitGirl Repack]", "SkateBIRD"],
    ["SOMA [FitGirl Repack]", "SOMA"],
    ["Spiritfarer [FitGirl Repack]", "Spiritfarer"],
    ["SPOOKWARE-DOGE", "SPOOKWARE"],
    ["Star Wars The Force Unleashed - [DODI Repack]", "Star Wars The Force Unleashed"],
    ["Star.Trek.Voyager.Elite.Force-GOG", "Star Trek Voyager Elite Force"],
    ["Subnautica.Below.Zero.v45588", "Subnautica Below Zero"],
    ["Subnautica.v68382", "Subnautica"],
    ["Surviving Mars [FitGirl Repack]", "Surviving Mars"],
    ["Tales of Arise [FitGirl Repack]", "Tales of Arise"],
    ["Airborne.Kingdom.v1.0.1", "Airborne Kingdom"],
    ["Dark Souls 3 [FitGirl Repack]", "Dark Souls 3"],
    ["Dark Souls Remastered [FitGirl Repack]", "Dark Souls Remastered"],
    [
        "Dark.Souls.II.Scholar.of.the.First.Sin-CODEX",
        "Dark Souls II Scholar of the First Sin",
    ],
    ["Factorio.v1.1.35", "Factorio"],
    [
        "Getting.Over.It.with.Bennett.Foddy.v1.5762",
        "Getting Over It with Bennett Foddy",
    ],
    ["GolfTopia", "GolfTopia"],
    ["HITMAN 3 [FitGirl Repack]", "HITMAN 3"],
    ["Industries.of.Titan.v0.11.0", "Industries of Titan"],
    ["Infinifactory.v1.0a-GOG", "Infinifactory"],
    [
        "Jurassic.World.Evolution.Complete.Edition-EMPRESS",
        "Jurassic World Evolution Complete Edition",
    ],
    ["Just Cause 4 - [EMPRESS DODI Repack]", "Just Cause 4"],
    ["Kaze and the Wild Masks [FitGirl Repack]", "Kaze and the Wild Masks"],
    ["Kerbal Space Program [FitGirl Repack]", "Kerbal Space Program"],
    [
        "Kingdom.Rush.Vengeance.Tower.Defense.PROPER-PLAZA",
        "Kingdom Rush Vengeance Tower Defense",
    ],
    [
        "Kingdoms of Amalur - Re-Reckoning [FitGirl Repack]",
        "Kingdoms of Amalur - Re-Reckoning",
    ],
    [
        "Kirby - The Complete Collection [FitGirl Repack]",
        "Kirby - The Complete Collection",
    ],
    ["Legend of Mana [FitGirl Repack]", "Legend of Mana"],
    ["Legends of Ellaria [FitGirl Repack]", "Legends of Ellaria"],
    [
        "Middle-earth - Shadow of War DE [FitGirl Repack]",
        "Middle-earth - Shadow of War DE",
    ],
    ["Minute.of.Islands-GOG", "Minute of Islands"],
    ["Mirror's Edge [Darck Repacks]", "Mirror's Edge"],
    ["Monster Hunter Rise [FitGirl Repack]", "Monster Hunter Rise"],
    ["MOTHERGUNSHIP-GOG", "MOTHERGUNSHIP"],
    ["Narita.Boy-GOG", "Narita Boy"],
    ["Noita.v12.03.2021", "Noita"],
    [
        "Offworld.Trading.Company.Interdimensional-CODEX",
        "Offworld Trading Company Interdimensional",
    ],
    ["Opus.Magnum.v11.14.2020", "Opus Magnum"],
    ["Ori and the Will of the Wisps [FitGirl Repack]", "Ori and the Will of the Wisps"],
    ["Outer.Wilds.v1.0.7", "Outer Wilds"],
    ["Planet Coaster [FitGirl Repack]", "Planet Coaster"],
    ["Planet Zoo [FitGirl Repack]", "Planet Zoo"],
    ["Planet.Coaster.Complete.Edition-EMPRESS", "Planet Coaster Complete Edition"],
    [
        "Planetary Annihilation - TITANS [FitGirl Repack]",
        "Planetary Annihilation - TITANS",
    ],
    ["Project.Wingmanv1.0.4D.REPACK-KaOs", "Project Wingman"],
    ["PULSAR - Lost Colony [FitGirl Repack]", "PULSAR - Lost Colony"],
    ["Rail.Route.Early.Access", "Rail Route"],
    ["Rain.On.Your.Parade", "Rain On Your Parade"],
    ["Reventure.v1.9.4", "Reventure"],
    ["rld-hodesokh13", "hodesokh13"],
    [
        "Rock.of.Ages.3.Make.and.Break.Hot.Potato-CODEX",
        "Rock of Ages 3 Make and Break Hot Potato",
    ],
    ["Shadow of the Tomb Raider [FitGirl Repack]", "Shadow of the Tomb Raider"],
    ["shapez.io.v1.4.1", "shapez io"],
    ["Sid Meier's Civilization 6 [FitGirl Repack]", "Sid Meier's Civilization 6"],
    ["space_colohy_hd_edcarnby", "space colohy hd"],
    ["Spellcaster.University-GOG", "Spellcaster University"],
    ["SpellForce_3_Fallen_God_v1.6-Razor1911", "SpellForce 3 Fallen God"],
    ["Spiritfarer.Lily-PLAZA", "Spiritfarer Lily"],
    ["Spiritfarer.v32698", "Spiritfarer"],
    ["sr-youropa", "youropa"],
    ["Stronghold.3-SKIDROW", "Stronghold 3"],
    ["Stronghold.Crusader.2", "Stronghold Crusader 2"],
    ["Supraland.Complete.Edition-PLAZA", "Supraland Complete Edition"],
    ["Supraland.v.1.8.2", "Supraland"],
    # ["t-strongholdcrusaderhdee", "strongholdcrusaderhdee"], # XXX garbage in garbage out
    ["Tachyon.Wars-DARKSiDERS", "Tachyon Wars"],
    ["The Last Campfire [FitGirl Repack]", "The Last Campfire"],
    [
        "The.Binding.of.Isaac.Rebirth.Repentance-PLAZA",
        "The Binding of Isaac Rebirth Repentance",
    ],
    ["The.Colonists.v1.5.11", "The Colonists"],
    ["The.Survivalists-PLAZA", "The Survivalists"],
    [
        "The_Dungeon_Of_Naheulbeuk_The_Amulet_Of_Chaos_v1.2.47.38606-Razor1911",
        "The Dungeon Of Naheulbeuk The Amulet Of Chaos",
    ],
    ["Timespinner.v1.032-SiMPLEX", "Timespinner"],
    ["Tony Hawk's Pro Skater 1 + 2 [FitGirl Repack]", "Tony Hawk's Pro Skater 1 + 2"],
    [
        "Totally.Reliable.Delivery.Service-DARKSiDERS",
        "Totally Reliable Delivery Service",
    ],
    ["Urban.Trial.Freestyle-GOG", "Urban Trial Freestyle"],
    ["Urban.Trial.Playground-GOG", "Urban Trial Playground"],
    ["Valheim.v0.148.7.Early.Access", "Valheim"],
    [
        "Wonder Boy - Asha in Monster World [FitGirl Repack]",
        "Wonder Boy - Asha in Monster World",
    ],
    ["Yakuza 6 - The Song of Life [FitGirl Repack]", "Yakuza 6 - The Song of Life"],
    ["Ys IX Monstrum Nox - [DODI Repack]", "Ys IX Monstrum Nox"],
    ["Ys VIII - Lacrimosa of DANA [FitGirl Repack]", "Ys VIII - Lacrimosa of DANA"],
    [
        "Age of Empires II - Definitive Edition [FitGirl Repack]",
        "Age of Empires II - Definitive Edition",
    ],
    [
        "Age.of.Empires.Definitive.Edition.Build.38862.REPACK2-KaOs",
        "Age of Empires Definitive Edition",
    ],
    ["Anno 1800 [FitGirl Repack]", "Anno 1800"],
    ["Axiom.Verge.2", "Axiom Verge 2"],
    ["Cyberpunk 2077 [FitGirl Repack]", "Cyberpunk 2077"],
    ["Demon's Souls [FitGirl Repack]", "Demon's Souls"],
    ["DOOM Eternal [FitGirl Repack]", "DOOM Eternal"],
    ["Dungeon Defenders - Awakened [FitGirl Repack]", "Dungeon Defenders - Awakened"],
    [
        "Final Fantasy VII - Remake Intergrade [FitGirl Repack]",
        "Final Fantasy VII - Remake Intergrade",
    ],
    ["Final Fantasy XIII [FitGirl Repack]", "Final Fantasy XIII"],
    ["FIST Forged In Shadow Torch - [DODI Repack]", "FIST Forged In Shadow Torch"],
    [
        "Five Nights at Freddy's - Security Breach [FitGirl Repack]",
        "Five Nights at Freddy's - Security Breach",
    ],
    ["Grand Theft Auto V - [DODI Repack]", "Grand Theft Auto V"],
    ["Halo Infinite [FitGirl Repack]", "Halo Infinite"],
    ["Heavenly.Bodies-CODEX", "Heavenly Bodies"],
    ["Hedon.Bloodrite-PLAZA", "Hedon Bloodrite"],
    ["Hoa [FitGirl Repack]", "Hoa"],
    ["Horror Tales - The Wine [FitGirl Repack]", "Horror Tales - The Wine"],
    ["Hot Lava [FitGirl Repack]", "Hot Lava"],
    ["Invasion", "Invasion"],
    ["Jupiter.Hell-CODEX", "Jupiter Hell"],
    ["Kill It With Fire [FitGirl Repack]", "Kill It With Fire"],
    ["MechWarrior 5 - Mercenaries [FitGirl Repack]", "MechWarrior 5 - Mercenaries"],
    [
        "Potion.Craft.Alchemist.Simulator.Early.Access",
        "Potion Craft Alchemist Simulator",
    ],
    ["Quake.II.RTX-GOG", "Quake II RTX"],
    [
        "Space.Rangers.HD.A.War.Apart.v2.1.2424.Hotfix-GOG",
        "Space Rangers HD A War Apart",
    ],
    ["SpellForce.3.Reforced-PLAZA", "SpellForce 3 Reforced"],
    [
        "Star Wars The Force Unleashed 2 - [DODI Repack]",
        "Star Wars The Force Unleashed 2",
    ],
    ["Stronghold - Warlords [FitGirl Repack]", "Stronghold - Warlords"],
    [
        "Super Monkey Ball - Banana Mania [FitGirl Repack]",
        "Super Monkey Ball - Banana Mania",
    ],
    ["The Ascent [FitGirl Repack]", "The Ascent"],
    ["The Falconeer [FitGirl Repack]", "The Falconeer"],
    ["The Forgotten City [FitGirl Repack]", "The Forgotten City"],
    [
        "The Great Ace Attorney Chronicles [FitGirl Repack]",
        "The Great Ace Attorney Chronicles",
    ],
    ["Thunder.Tier.One-CODEX", "Thunder Tier One"],
    ["Toodee.and.Topdee-DARKZER0", "Toodee and Topdee"],
    ["Voxel.Tycoon.v0.86.1", "Voxel Tycoon"],
    ["Wasteland 3 [FitGirl Repack]", "Wasteland 3"],
    ["Watchs.Dogs.Legion-EMPRESS [English Repack]", "Watchs Dogs Legion"],
    ["Xenoblade Chronicles 2 [FitGirl Repack]", "Xenoblade Chronicles 2"],
    ["ZEROED-DARKSiDERS", "ZEROED"],
    ["A Little Golf Journey [FitGirl Repack]", "A Little Golf Journey"],
    [
        "Ace Combat 7 Skies Unknown Deluxe Edition - [DODI Repack]",
        "Ace Combat 7 Skies Unknown Deluxe Edition",
    ],
    ["Act.Of.War.Gold.Edition.(2005).REPACK-KaOs", "Act Of War Gold Edition"],
    ["Age of Empires IV - [DODI Repack]", "Age of Empires IV"],
    ["Age of Empires IV [FitGirl Repack]", "Age of Empires IV"],
    [
        "Age.of.Mythology.Extended.Edition.Tale.of.the.Dragon.v2.8.REPACK-KaOs",
        "Age of Mythology Extended Edition Tale of the Dragon",
    ],
    ["Airport.CEO-TiNYiSO", "Airport CEO"],
    ["Aliens - Fireteam Elite [FitGirl Repack]", "Aliens - Fireteam Elite"],
    ["Amazing_cultivation.Simulator.v1.211-GOG", "Amazing cultivation Simulator"],
    ["AMID.EVIL.v2172c.REPACK-KaOs", "AMID EVIL"],
    ["Anno - History Collection [FitGirl Repack]", "Anno - History Collection"],
    ["Anno 2205 Gold Edition by xatab", "Anno 2205 Gold Edition"],
    ["Anno.1404.Gold.Edition-GOG", "Anno 1404 Gold Edition"],
    ["Archvale [FitGirl Repack]", "Archvale"],
    ["Ashen by xatab", "Ashen"],
    ["Astalon.Tears.of.the.Earth-GOG", "Astalon Tears of the Earth"],
    ["Astral Chain [FitGirl Repack]", "Astral Chain"],
    ["ATOM.RPG.Trudograd.v0.9.2-GOG", "ATOM RPG Trudograd"],
    ["Atomicrops [FitGirl Repack]", "Atomicrops"],
    ["Baldur's Gate 3", "Baldur's Gate 3"],
    ["BattleZone.98.Redux.v2.2.301.REPACK-KaOs", "BattleZone 98 Redux"],
    ["Beacon [FitGirl Repack]", "Beacon"],
    [
        "BioShock Infinite - The Complete Edition [FitGirl Repack]",
        "BioShock Infinite - The Complete Edition",
    ],
    ["BioShock.2.Remastered-CODEX", "BioShock 2 Remastered"],
    ["BioShock.Remastered-CODEX", "BioShock Remastered"],
    ["Black Book [FitGirl Repack]", "Black Book"],
    [
        "Black Mesa - Definitive Edition [FitGirl Repack]",
        "Black Mesa - Definitive Edition",
    ],
    ["Blade of God [FitGirl Repack]", "Blade of God"],
    ["Blasphemous - [DODI Repack]", "Blasphemous"],
    ["Blasphemous.Wounds.of.Eventide-CODEX", "Blasphemous Wounds of Eventide"],
    ["BloodRayne_Betrayal_Fresh_Bites-Razor1911", "BloodRayne Betrayal Fresh Bites"],
    ["Blue Fire [FitGirl Repack]-1", "Blue Fire"],
    ["Boomerang X [FitGirl Repack]", "Boomerang X"],
    ["Boppio.Beta", "Boppio Beta"],
    ["Bravely Default II [FitGirl Repack]", "Bravely Default II"],
    ["Breathedge [FitGirl Repack]", "Breathedge"],
    ["Bright Memory - Infinite [FitGirl Repack]", "Bright Memory - Infinite"],
    ["Cadence of Hyrule [FitGirl Repack]", "Cadence of Hyrule"],
    ["CARRION [FitGirl Repack]", "CARRION"],
    ["Cave.Story-GOG", "Cave Story"],
    ["Chorus [FitGirl Repack]", "Chorus"],
    ["Clid The Snail [FitGirl Repack]", "Clid The Snail"],
    ["Clone.Drone.in.the.Danger.Zone-PLAZA", "Clone Drone in the Danger Zone"],
    ["Cloudpunk [FitGirl Repack]", "Cloudpunk"],
    ["Clustertruck [Other s]", "Clustertruck"],
    ["codex-hello.neighbor.v1.1.9", "hello neighbor"],
    ["codex-unravel.two", "unravel two"],
    ["Control [FitGirl Repack]", "Control"],
    ["Crash Drive 3 - [DODI Repack]-1", "Crash Drive 3"],
    ["Creeper_World_4_v2.0.1-Razor1911", "Creeper World 4"],
    ["Curved Space [FitGirl Repack]", "Curved Space"],
    ["Custodian.Beginning.of.the.End-DARKZER0", "Custodian Beginning of the End"],
    ["Dead Cells - [DODI Repack]", "Dead Cells"],
    ["Dead Cells [FitGirl Repack]", "Dead Cells"],
    ["Death's Door [FitGirl Repack]", "Death's Door"],
    ["Death's Gambit - Afterlife [FitGirl Repack]", "Death's Gambit - Afterlife"],
    ["Deep Rock Galactic [FitGirl Repack]", "Deep Rock Galactic"],
    ["Demon Skin [FitGirl Repack]", "Demon Skin"],
    ["Demon.Turf-DOGE", "Demon Turf"],
    ["Descenders.The.Grand.Tour-PLAZA", "Descenders The Grand Tour"],
    ["Devil.Slayer.Raksasi.v1.2.2-PLAZA", "Devil Slayer Raksasi"],
    ["Dicey.Dungeons-GOG", "Dicey Dungeons"],
    [
        "Dishonored - Death of the Outsider [FitGirl Repack]",
        "Dishonored - Death of the Outsider",
    ],
    ["Dishonored 2 [FitGirl Repack]", "Dishonored 2"],
    ["Dishonored-SKIDROW", "Dishonored"],
    ["DOOM", "DOOM"],
    ["Doom.3.BFG.Edition.v1.14.REPACK-KaOs-1", "Doom 3 BFG Edition"],
    [
        "Dr Kawashima's Brain Training for Nintendo Switch [NSP + XCI + Update 1.0.2]",
        "Dr Kawashima's Brain Training for Nintendo Switch",
    ],
    ["Dragon Quest Builders 2 [FitGirl Repack]", "Dragon Quest Builders 2"],
    ["DUSK.v1.7.24-GOG", "DUSK"],
    ["Eastern Exorcist [FitGirl Repack]", "Eastern Exorcist"],
    ["Embr [FitGirl Repack]", "Embr"],
    ["Epic Chef [FitGirl Repack]", "Epic Chef"],
    ["Eximius - Seize the Frontline [FitGirl Repack]", "Eximius - Seize the Frontline"],
    ["Exo.One-CODEX", "Exo One"],
    ["Exodus.Borealis-PLAZA", "Exodus Borealis"],
    ["Factory.Town.v1.8.2-SiMPLEX", "Factory Town"],
    ["Far Cry 3 Complete Collection - CorePack", "Far Cry 3 Complete Collection"],
    ["Far Cry 5 [FitGirl Repack]-1", "Far Cry 5"],
    [
        "Field.of.Glory.Empires.Persia.550-330.BCE-PLAZA",
        "Field of Glory Empires Persia 550-330 BCE",
    ],
    ["Fights.in.Tight.Spaces-PLAZA", "Fights in Tight Spaces"],
    ["FIST Forged In Shadow Torch - [DODI Repack]", "FIST Forged In Shadow Torch"],
    ["Foregone.v1.1-GOG", "Foregone"],
    ["Forza Horizon 4 [FitGirl Repack]", "Forza Horizon 4"],
    ["Forza Horizon 5 [FitGirl Repack]", "Forza Horizon 5"],
    [
        "Galactic.Civilizations.3.III.Worlds.In.Crisis.v4.2.23169.REPACK-KaOs",
        "Galactic Civilizations 3 III Worlds In Crisis",
    ],
    ["Gears 5 - GotY Edition [FitGirl Repack]", "Gears 5 - GotY Edition"],
    ["Ghostrunner.v41955.440-GOG", "Ghostrunner"],
    ["Glyph-PLAZA", "Glyph"],
    ["Graveyard Keeper [FitGirl Repack]", "Graveyard Keeper"],
    ["GreedFall - Gold Edition [FitGirl Repack]", "GreedFall - Gold Edition"],
    ["Grim.Dawn.Definitive.Edition.v1.1.9.4-GOG", "Grim Dawn Definitive Edition"],
    ["GRIP-GOG", "GRIP"],
    ["GRIS - [DODI Repack]", "GRIS"],
    ["Gunfire Reborn [FitGirl Repack]", "Gunfire Reborn"],
    ["Halo - TMCC [FitGirl Repack]", "Halo - TMCC"],
    ["Hearts of Iron IV [FitGirl Repack]", "Hearts of Iron IV"],
    ["Hellblade - Senua's Sacrifice [FitGirl Repack]", "Hellblade - Senua's Sacrifice"],
    ["Highrise.Mogul-PLAZA", "Highrise Mogul"],
    ["hlm-frzn", "hlm-frzn"],
    ["Hobo Cat Adventures [FitGirl Repack]", "Hobo Cat Adventures"],
    ["HUMANKIND [FitGirl Repack]", "HUMANKIND"],
    ["Hydroneer [FitGirl Repack]", "Hydroneer"],
    ["Hyrule Warriors Age of Calamity (XCI)", "Hyrule Warriors Age of Calamity"],
    ["InfraSpace.v8.1.184-GOG", "InfraSpace"],
    ["Insurgency Sandstorm - [DODI Repack]", "Insurgency Sandstorm"],
    ["Just_Cause_2_1.0.0.2_(50335)_win_gog", "Just Cause 2"],
    ["Kenshi.v1.0.55jp-GOG", "Kenshi"],
    ["Kingdom Two Crowns - [DODI Repack]", "Kingdom Two Crowns"],
    ["Kingdom.Rush.Vengeance-GOG", "Kingdom Rush Vengeance"],
    [
        "Kingdoms of Amalur - Re-Reckoning [FitGirl Repack]",
        "Kingdoms of Amalur - Re-Reckoning",
    ],
    ["Left 4 Dead - [DODI Repack]", "Left 4 Dead"],
    ["Legend of Mana - PC [FitGirl Repack]", "Legend of Mana - PC"],
    [
        "Legend.of.Keepers.Career.of.a.Dungeon.Manager.Return.of.the.Goddess.Update.v1.0.8-PLAZA",
        "Legend of Keepers Career of a Dungeon Manager Return of the Goddess",
    ],
    ["Lemnis Gate - [DODI Repack]", "Lemnis Gate"],
    ["Library.Of.Ruina-CODEX", "Library Of Ruina"],
    ["Lifeslide [FitGirl Repack]", "Lifeslide"],
    ["Loop.Hero", "Loop Hero"],
    ["Luigi's Mansion 3 [NSP]", "Luigi's Mansion 3"],
    ["Mafia.II.Directors.Cut-GOG", "Mafia II Directors Cut"],
    ["Mario Party Superstars [FitGirl Repack]", "Mario Party Superstars"],
    ["MechWarrior 5 - Mercenaries [FitGirl Repack]", "MechWarrior 5 - Mercenaries"],
    ["MechWarrior 5 - Mercenaries [FitGirl Repack]-1", "MechWarrior 5 - Mercenaries"],
    [
        "Metal Gear Solid V The Phantom Pain - [DODI Repack]",
        "Metal Gear Solid V The Phantom Pain",
    ],
    ["Minecraft 1.16 [Full, Online, Server List]", "Minecraft"],
    ["Minecraft.Dungeons.Cloudy.Climb-CODEX", "Minecraft Dungeons Cloudy Climb"],
    ["Mini Racing World [FitGirl Repack]", "Mini Racing World"],
    ["Mirror's Edge Catalyst - [DODI Repack]", "Mirror's Edge Catalyst"],
    ["Moncage-PLAZA", "Moncage"],
    ["Monster Hunter Stories 2 [FitGirl Repack]", "Monster Hunter Stories 2"],
    ["MOTHERGUNSHIP.Build.7849592-TiNYiSO", "MOTHERGUNSHIP"],
    ["Moving.Out-SiMPLEX", "Moving Out"],
    ["mw_remastered", "mw remastered"],
    ["NEO - TWEWY [FitGirl Repack]", "NEO - TWEWY"],
    ["Neon.Chrome.v1.1.7", "Neon Chrome"],
    ["New.Super.Luckys.Tale.v1.1.82.REPACK-KaOs", "New Super Luckys Tale"],
    ["NieR Replicant - [DODI Repack]", "NieR Replicant"],
    [
        "NieR.Automata.Game.of.the.YoRHa.Edition-CODEX",
        "NieR Automata Game of the YoRHa Edition",
    ],
    ["Northgard.Krowns.and.Daggers-PLAZA", "Northgard Krowns and Daggers"],
    ["Nyctophobia.Devil.Unleashed-DARKSiDERS", "Nyctophobia Devil Unleashed"],
    ["Orcs Must Die 3 [FitGirl Repack]", "Orcs Must Die 3"],
    ["Ostriv.v0.4.5.1-GOG", "Ostriv"],
    ["Overcooked! 2 [FitGirl Repack]", "Overcooked! 2"],
    ["Overcooked! All You Can Eat [FitGirl Repack]", "Overcooked! All You Can Eat"],
    ["Overpower-PLAZA-1", "Overpower"],
    ["Owlboy", "Owlboy"],
    ["Painkiller - Complete Pack [FitGirl Repack]", "Painkiller - Complete Pack"],
    ["Paint the Town Red [FitGirl Repack]", "Paint the Town Red"],
    ["Panzer Corps 2 [FitGirl Repack]", "Panzer Corps 2"],
    ["Panzer.Dragoon.Remake.v1.4.2.REPACK-KaOs", "Panzer Dragoon Remake"],
    ["Paper Mario The Origami King [NSP][XCI]", "Paper Mario The Origami King"],
    ["Party Hard 2 [FitGirl Repack]", "Party Hard 2"],
    ["Patron.v1.050.1-GOG", "Patron"],
    ["Pax Nova [FitGirl Repack]", "Pax Nova"],
    ["Per Aspera [FitGirl Repack]", "Per Aspera"],
    ["Phoenotopia.Awakening-GOG", "Phoenotopia Awakening"],
    ["Pokemon BD-SP [FitGirl Repack]", "Pokemon BD-SP"],
    [
        "Pokemon Mystery Dungeon Rescue Team DX + Update [NSP]",
        "Pokemon Mystery Dungeon Rescue Team DX +",
    ],
    ["Praey for the Gods [FitGirl Repack]", "Praey for the Gods"],
    ["Pronty.Fishy.Adventure-CODEX", "Pronty Fishy Adventure"],
    ["Psychonauts 2 [FitGirl Repack]", "Psychonauts 2"],
    ["Railroad Corporation [FitGirl Repack]", "Railroad Corporation"],
    [
        "Railroad.Corporation.Complete.Collection-SKIDROW",
        "Railroad Corporation Complete Collection",
    ],
    [
        "Record.of.Lodoss.War.Deedlit.in.Wonder.Labyrinth.0.6.2.8",
        "Record of Lodoss War Deedlit in Wonder Labyrinth",
    ],
    ["Red Dead Redemption 2 [FitGirl Repack]", "Red Dead Redemption 2"],
    ["Red.Faction.Armageddon.v1.01.REPACK-KaOs", "Red Faction Armageddon"],
    ["Resident.Evil.Village.Animation.Fix-EMPRESS", "Resident Evil Village"],
    ["Resistance - Fall of Man [FitGirl Repack]", "Resistance - Fall of Man"],
    ["Resistance 2 [FitGirl Repack]", "Resistance 2"],
    ["Resistance 3 [FitGirl Repack]", "Resistance 3"],
    [
        "Return.to.Castle.Wolfenstein.v2.0.0.2.REPACK-KaOs",
        "Return to Castle Wolfenstein",
    ],
    ["rld-snake.pass.v14", "snake pass"],
    ["rzr-verletswing", "verletswing"],
    [
        "Saints Row - The Third Remastered [FitGirl Repack]",
        "Saints Row - The Third Remastered",
    ],
    ["Scarlet Nexus [FitGirl Repack]", "Scarlet Nexus"],
    [
        "Shadow Tactics - Aiko's Choice [FitGirl Repack]",
        "Shadow Tactics - Aiko's Choice",
    ],
    ["Shadow Tactics Aikos Choice - [DODI Repack]", "Shadow Tactics Aikos Choice"],
    ["Shadow.Man.Remastered.v1.11.REPACK-KaOs-1", "Shadow Man Remastered"],
    ["Shantae_And_The_Seven_Sirens_v731089-Razor1911", "Shantae And The Seven Sirens"],
    ["SHENZHEN IO [GOG]", "SHENZHEN IO"],
    ["Sim City 4 Deluxe Edition {MULTI 12} {TJ}", "Sim City 4 Deluxe Edition"],
    ["Sin and Punishment 2 [R2VP01]", "Sin and Punishment 2"],
    ["Skul The Hero Slayer v.1.3.2 [build 6984462] (2021)", "Skul The Hero Slayer"],
    ["Skydrift Infinity [FitGirl Repack]", "Skydrift Infinity"],
    ["Solar Ash [FitGirl Repack]", "Solar Ash"],
    [
        "Solasta - Crown of the Magister [FitGirl Repack]",
        "Solasta - Crown of the Magister",
    ],
    ["Songs for a Hero - DE [FitGirl Repack]", "Songs for a Hero - DE"],
    [
        "Space Crew - Legendary Edition [FitGirl Repack]",
        "Space Crew - Legendary Edition",
    ],
    ["Spiritfarer [FitGirl Repack]", "Spiritfarer"],
    ["Star Drift Evolution [FitGirl Repack]", "Star Drift Evolution"],
    ["Star Wars Jedi - Fallen Order [FitGirl Repack]", "Star Wars Jedi - Fallen Order"],
    ["Stardew.Valley.v1.5.5.1835528477-GOG", "Stardew Valley"],
    ["Steel_Division_2_51957_(47364)_win_gog-1", "Steel Division 2"],
    ["Stellaris [FitGirl Repack]", "Stellaris"],
    ["Streets_of_Rogue_95_(48531)_win_gog", "Streets of Rogue"],
    [
        "Super Mario 3D World + Bowser's Fury [FitGirl Repack]",
        "Super Mario 3D World + Bowser's Fury",
    ],
    ["Superliminal [FitGirl Repack]", "Superliminal"],
    ["Superliminal [FitGirl Repack]-1", "Superliminal"],
    ["Surgeon_Simulator_2-FLT", "Surgeon Simulator 2"],
    ["Tales of Arise - [DODI Repack]", "Tales of Arise"],
    ["The Ascent [FitGirl Repack]", "The Ascent"],
    [
        "The Legend of Zelda - Links Awakening [FitGirl Repack]",
        "The Legend of Zelda - Links Awakening",
    ],
    ["The Rewinder [FitGirl Repack]", "The Rewinder"],
    ["The Sims 4 [anadius Repack]", "The Sims 4"],
    [
        "The Witcher 2 - Enhanced Edition - [DODI Repack]",
        "The Witcher 2 - Enhanced Edition",
    ],
    ["The.Eternal.Cylinder.REPACK-KaOs", "The Eternal Cylinder"],
    ["The.Legend.of.Tianding-CODEX", "The Legend of Tianding"],
    ["The.Riftbreaker-GOG", "The Riftbreaker"],
    [
        "The.Witcher.3.Wild.Hunt.GOTY.Edition.V1.32.REPACK-KaOs",
        "The Witcher 3 Wild Hunt GOTY Edition",
    ],
    [
        "There_Is_No_Game_Wrong_Dimension_v1.0.29-Razor1911",
        "There Is No Game Wrong Dimension",
    ],
    ["Thunder Tier One [FitGirl Repack]", "Thunder Tier One"],
    [
        "Tiny Tina's Assault on Dragon Keep [FitGirl Repack]",
        "Tiny Tina's Assault on Dragon Keep",
    ],
    [
        "Titan Quest - Anniversary Edition [FitGirl Repack]",
        "Titan Quest - Anniversary Edition",
    ],
    [
        "Titan Quest Anniversary Edition - [DODI Repack]",
        "Titan Quest Anniversary Edition",
    ],
    [
        "Titan.Quest.Anniversary.Edition.Eternal.Embers-PLAZA",
        "Titan Quest Anniversary Edition Eternal Embers",
    ],
    ["Tormented Souls [FitGirl Repack]", "Tormented Souls"],
    ["Total War WARHAMMER II - [DODI Repack]", "Total War WARHAMMER II"],
    [
        "Total.War.ROM.Remastered.Enhanced.Graphics.Pack.REPACK-KaOs",
        "Total War ROM Remastered Enhanced Graphics Pack",
    ],
    ["Trailmakers [FitGirl Repack]", "Trailmakers"],
    ["Transport.Fever.2.v33872-GOG", "Transport Fever 2"],
    ["Tropico.6.Vigilancia.y.Seguridad-CODEX", "Tropico 6"],
    [
        "Universe.At.War.Earth.Assault.Gold.Final.(2007).REPACK-KaOs",
        "Universe At War Earth Assault Gold Final",
    ],
    ["Unpacking [FitGirl Repack]", "Unpacking"],
    ["Urban.Trial.Tricky.Deluxe.Edition-DOGE", "Urban Trial Tricky Deluxe Edition"],
    ["Vaporum - Lockdown [FitGirl Repack]", "Vaporum - Lockdown"],
    ["Vigil.The.Longest.Night.Asomrof-PLAZA", "Vigil The Longest Night Asomrof"],
    [
        "Warhammer 40000 - Battlesector [FitGirl Repack]",
        "Warhammer 40000 - Battlesector",
    ],
    ["Warhammer 40K - Gladius [FitGirl Repack]", "Warhammer 40K - Gladius"],
    ["Wolfenstein The New Order - [DODI Repack]", "Wolfenstein The New Order"],
    ["Wuppo.Definitive.Edition.v1.0.37-PLAZA", "Wuppo Definitive Edition"],
    ["X3.Farnhams.Legacy-PLAZA", "X3 Farnhams Legacy"],
    ["X3.Farnhams.Legacy.Update.v1.3-PLAZA", "X3 Farnhams Legacy"],
    ["X4.Foundations.Cradle.of.Humanity-CODEX", "X4 Foundations Cradle of Humanity"],
    ["Xenoblade Chronicles - DE [FitGirl Repack]", "Xenoblade Chronicles - DE"],
    ["Yakuza 0 [FitGirl Repack]", "Yakuza 0"],
    ["Yoku's Island Express [FitGirl Repack]", "Yoku's Island Express"],
    ["Ziggurat.2-PLAZA", "Ziggurat 2"],
    [
        "[ELECTRO-TORRENT.PL]Ori And The Blind - Forest Definitive Edition",
        "Ori And The Blind - Forest Definitive Edition",
    ],
    ["Aery - Calm Mind [FitGirl Repack]", "Aery - Calm Mind"],
    ["Alone.on.Mars-Unleashed", "Alone on Mars"],
    ["Bomb.Chicken", "Bomb Chicken"],
    ["Boomerang X [FitGirl Repack]", "Boomerang X"],
    ["BPM - Bullets Per Minute [FitGirl Repack]", "BPM - Bullets Per Minute"],
    ["Brigador_1.62d_(49245)_win_gog", "Brigador"],
    ["Children of Morta [FitGirl Repack]", "Children of Morta"],
    ["Cosmos.Quickstop-DOGE", "Cosmos Quickstop"],
    ["DEVOUR.The.Inn-PLAZA", "DEVOUR The Inn"],
    ["Fuga.Melodies.of.Steel-DARKSiDERS", "Fuga Melodies of Steel"],
    ["Growbot [FitGirl Repack]", "Growbot"],
    ["Hot Wheels Unleashed [FitGirl Repack]", "Hot Wheels Unleashed"],
    ["Hourglass [FitGirl Repack]", "Hourglass"],
    ["Killsquad [FitGirl Repack]", "Killsquad"],
    ["Mad Wild Fairy Tale [FitGirl Repack]", "Mad Wild Fairy Tale"],
    ["Mail Mole [FitGirl Repack]", "Mail Mole"],
    ["Mecha Knights - Nightmare [FitGirl Repack]", "Mecha Knights - Nightmare"],
    ["METAL_GEAR_SOLID_1.0.cu_(44646)_win_gog", "METAL GEAR SOLID"],
    ["Mini.Motorways.v10.08.2021", "Mini Motorways"],
    ["Omno-CODEX", "Omno"],
    ["Persona 5 [FitGirl Repack]", "Persona 5"],
    ["Quake - Enhanced [FitGirl Repack]", "Quake - Enhanced"],
    ["Quake.Collection", "Quake Collection"],
    ["Resident Evil Village - [DODI Repack]", "Resident Evil Village"],
    ["Samurai Warriors 5 [FitGirl Repack]", "Samurai Warriors 5"],
    ["Space.Crew.Legendary.Edition-PLAZA", "Space Crew Legendary Edition"],
    ["SPORE™ Collection [GOG]", "SPORE™ Collection"],
    ["Strategic_Mind_Fight_for_Freedom_v1_06-FLT", "Strategic Mind Fight for Freedom"],
    ["The.Vale.Shadow.of.the.Crown-DOGE", "The Vale Shadow of the Crown"],
    ["Tinytopia [FitGirl Repack]", "Tinytopia"],
    ["Trackmania.Turbo-CODEX", "Trackmania Turbo"],
    [
        "TrackMania.United.Forever.Star.Edition-PiNDASAUS",
        "TrackMania United Forever Star Edition",
    ],
    ["Tropico.6.Festival.REPACK-KaOs", "Tropico 6 Festival"],
    ["Twelve Minutes [FitGirl Repack]", "Twelve Minutes"],
    ["Wargame - Red Dragon [FitGirl Repack]", "Wargame - Red Dragon"],
    [
        "Wolfenstein. Blade of Agony v.3.0+3.1 [Realm667] (2021)",
        "Wolfenstein Blade of Agony",
    ],
    ["Xenia's Ark [FitGirl Repack]", "Xenia's Ark"],
    ["A Hat in Time [FitGirl Repack]", "A Hat in Time"],
    ["A.Short.Hike.v1.8.14", "A Short Hike"],
    ["Action.Commando-DOGE", "Action Commando"],
    ["Alba.A.Wildlife.Adventure-GOG", "Alba A Wildlife Adventure"],
    ["Alien Isolation - [DODI Repack]", "Alien Isolation"],
    [
        "An.Airport.for.Aliens.Currently.Run.by.Dogs.REPACK-DARKSiDERS",
        "An Airport for Aliens Currently Run by Dogs",
    ],
    [
        "Baldurs_Gate_II_Enhanced_Edition_2.6.6.0_(46870)_win_gog",
        "Baldurs Gate II Enhanced Edition",
    ],
    ["Barony.Legends.and.Pariahs.v3.3.4-SiMPLEX", "Barony Legends and Pariahs"],
    [
        "Bloodstained - Ritual of the Night [FitGirl Repack]",
        "Bloodstained - Ritual of the Night",
    ],
    [
        "Bloodstained.Ritual.of.the.Night.Classic.Mode.Update.v1.21.0.1-CODEX",
        "Bloodstained Ritual of the Night Classic Mode",
    ],
    ["Braid [MULTI9][PC][Mouladi]", "Braid"],
    ["Brass.Brigade.Okinawa-PLAZA", "Brass Brigade Okinawa"],
    ["Call To Arms Gates of Hell", "Call To Arms Gates of Hell"],
    ["Chicory - A Colorful Tale [FitGirl Repack]", "Chicory - A Colorful Tale"],
    ["Cities - Skylines [FitGirl Repack]", "Cities - Skylines"],
    ["Class.of.09-DARKSiDERS", "Class of 09"],
    ["Code Vein [FitGirl Repack]", "Code Vein"],
    ["Cruelty.Squad-DARKZER0", "Cruelty Squad"],
    ["Dead Space 2 [FitGirl Repack]", "Dead Space 2"],
    ["Dead Space 3 [FitGirl Repack]", "Dead Space 3"],
    ["Dead Space [FitGirl Repack]", "Dead Space"],
    ["Deliver.Us.The.Moon.v1.4.4-CODEX", "Deliver Us The Moon"],
    ["Devil.Daggers.v3.1-GOG", "Devil Daggers"],
    ["Diablo II + LoD", "Diablo II + LoD"],
    ["Dieselpunk Wars [FitGirl Repack]", "Dieselpunk Wars"],
    ["Disco.Elysium.The.Final.Cut.v2832f901-CODEX", "Disco Elysium The Final Cut"],
    ["Divinity - Original Sin 2 by xatab", "Divinity - Original Sin 2"],
    [
        "Divinity.Original.Sin.Enhanced.Edition.MULTi9-PROPHET",
        "Divinity Original Sin Enhanced Edition",
    ],
    ["Dragon.Quest.Builders.2.v20210428", "Dragon Quest Builders 2"],
    ["Dust_An_Elysian_Tail_1.0_(20823)_win_gog", "Dust An Elysian Tail"],
    [
        "Dying Light - The Following EE [FitGirl Repack]",
        "Dying Light - The Following EE",
    ],
    [
        "Earth Defense Force - World Brothers [FitGirl Repack]",
        "Earth Defense Force - World Brothers",
    ],
    ["Element.TD.2.Update.v1.1-PLAZA", "Element TD 2"],
    [
        "ENDER.LILIES.Quietus.of.the.Knights.v0.7.1",
        "ENDER LILIES Quietus of the Knights",
    ],
    ["Endless Space 2 [FitGirl Repack]", "Endless Space 2"],
    ["Environmental.Station.Alpha.v06.02.2020", "Environmental Station Alpha"],
    [
        "Escape.the.Ayuwoki.The.Summoning.Update.v1.5-CODEX",
        "Escape the Ayuwoki The Summoning",
    ],
    [
        "Europa.Universalis.IV.Leviathan.Update.v1.31.1.INCL.DLC.REPACK-KaOs",
        "Europa Universalis IV Leviathan",
    ],
    ["Far Cry 3 - Duology [FitGirl Repack]", "Far Cry 3 - Duology"],
    ["FEZ", "FEZ"],
    ["Fictorum [FitGirl Repack]", "Fictorum"],
    ["Foundation_alpha 1.7.10.0630_(48158)_win_dev_gog", "Foundation"],
    [
        "Frostpunk.Game.of.the.Year.Edition.v1.6.1-GOG",
        "Frostpunk Game of the Year Edition",
    ],
    ["Galactic Civilizations III [FitGirl Repack]", "Galactic Civilizations III"],
    ["Gato.Roboto-SiMPLEX", "Gato Roboto"],
    ["Gazmatera.Return.of.the.Generals-PLAZA", "Gazmatera Return of the Generals"],
    ["GemCraft.Frostborn.Wrath.v1.2.1a", "GemCraft Frostborn Wrath"],
    ["Going.Medieval.v0.5.27.3", "Going Medieval"],
    ["GoNNER_2-DINOByTES", "GoNNER 2"],
    ["Grand.Casino.Tycoon-TiNYiSO", "Grand Casino Tycoon"],
    ["Grim Dawn [FitGirl Repack]", "Grim Dawn"],
    ["Guacamelee.2.Complete.Edition-TiNYiSO", "Guacamelee 2 Complete Edition"],
    ["Hades.v1.37996", "Hades"],
    ["Halo Wars 2 [FitGirl Repack]", "Halo Wars 2"],
    ["Halo.Wars.Definitive.Edition-CODEX", "Halo Wars Definitive Edition"],
    ["HELLDIVERS.Dive.Harder-PLAZA", "HELLDIVERS Dive Harder"],
    ["Hitman.3.Update.v3.40.0-CODEX", "Hitman 3"],
    ["Hollow Knight [FitGirl Repack]", "Hollow Knight"],
    ["Homeworld Remastered Collection", "Homeworld Remastered Collection"],
    ["Horizon.Zero.Dawn.Complete.Edition-GOG", "Horizon Zero Dawn Complete Edition"],
    ["Human - Fall Flat [FitGirl Repack]", "Human - Fall Flat"],
    ["HYPERCHARGE - Unboxed [FitGirl Repack]", "HYPERCHARGE - Unboxed"],
    ["Immortals Fenyx Rising - [Tiny Repack]", "Immortals Fenyx Rising"],
    ["Insurmountable [FitGirl Repack]", "Insurmountable"],
    ["Iron Harvest [FitGirl Repack]-1", "Iron Harvest"],
    ["Just Die Already [FitGirl Repack]", "Just Die Already"],
    ["LEGO Builder's Journey [FitGirl Repack]", "LEGO Builder's Journey"],
    ["Lumberhill-PLAZA", "Lumberhill"],
    ["Mad Devils [FitGirl Repack]", "Mad Devils"],
    ["Metro - Exodus EE [FitGirl Repack]", "Metro - Exodus EE"],
    ["Minecraft.Dungeons.Hidden.Depths-CODEX", "Minecraft Dungeons Hidden Depths"],
    [
        "Monster Hunter World - Iceborne HRTP [FitGirl Repack]",
        "Monster Hunter World - Iceborne HRTP",
    ],
    [
        "Monster Hunter World - Iceborne [FitGirl Repack]",
        "Monster Hunter World - Iceborne",
    ],
    [
        "Moonlighter_Between_Dimensions_v1.14.29-DINOByTES",
        "Moonlighter Between Dimensions",
    ],
    ["Necromunda - Hired Gun [FitGirl Repack]", "Necromunda - Hired Gun"],
    [
        "Need for Speed Underground 2 Remastered - [DODI Repack]",
        "Need for Speed Underground 2 Remastered",
    ],
    ["New Pokemon Snap [FitGirl Repack]", "New Pokemon Snap"],
    ["Night.Delivery.v1.09", "Night Delivery"],
    [
        "NINJA GAIDEN - Master Collection [FitGirl Repack]",
        "NINJA GAIDEN - Master Collection",
    ],
    ["No More Heroes 2", "No More Heroes 2"],
    ["No More Heroes [FitGirl Repack]", "No More Heroes"],
    ["Nova.Drift.v13.04.2021", "Nova Drift"],
    ["Now Testing - 407 [FitGirl Repack]", "Now Testing - 407"],
    ["Orcs_Must_Die_2-FLT", "Orcs Must Die 2"],
    ["Ori and the Will of the Wisps", "Ori and the Will of the Wisps"],
    ["Pillars of Eternity 2 [FitGirl Repack]", "Pillars of Eternity 2"],
    ["Pillars of Eternity [FitGirl Repack]", "Pillars of Eternity"],
    [
        "plaza-fortresscraft.evolved.adventures.pack",
        "fortresscraft evolved adventures pack",
    ],
    [
        "plaza-sins.of.a.solar.empire.rebellion.minor.factions",
        "sins of a solar empire rebellion minor factions",
    ],
    ["Prey [FitGirl Repack]", "Prey"],
    ["Prodeus.v0.1.10b-GOG", "Prodeus"],
    ["Proteus.v1.0.full-THETA", "Proteus"],
    ["Railway Empire [FitGirl Repack]", "Railway Empire"],
    ["Refunct-SiMPLEX", "Refunct"],
    ["Remnant - From the Ashes [FitGirl Repack]", "Remnant - From the Ashes"],
    ["Resident Evil 7 - Biohazard [FitGirl Repack]", "Resident Evil 7 - Biohazard"],
    ["Rogue.Legacy.2.v0.4.3a", "Rogue Legacy 2"],
    ["Rolling.Line.Santa.Fe.Remaster-PLAZA", "Rolling Line Santa Fe Remaster"],
    ["RUINER [FitGirl Repack]", "RUINER"],
    ["Saints.Row.The.Third.Remastered.v1.0.6.1-GOG", "Saints Row The Third Remastered"],
    ["Shadow Warrior 2 [FitGirl Repack]", "Shadow Warrior 2"],
    ["shapez.io.v1.3.1", "shapez io"],
    [
        "Sid.Meiers.Civilization.V.Brave.New.World-RELOADED",
        "Sid Meiers Civilization V Brave New World",
    ],
    [
        "Silent Hill 2 Enhanced Edition - [DODI Repack]",
        "Silent Hill 2 Enhanced Edition",
    ],
    ["Sleeping_Dogs_1.0_(45681)_win_gog", "Sleeping Dogs"],
    ["Sorcs.Siege.Chronicles-TiNYiSO", "Sorcs Siege Chronicles"],
    ["Spec Ops - The Line - [DODI Repack]", "Spec Ops - The Line"],
    ["Star Wars - Republic Commando 2.0.0.6 [GOG]", "Star Wars - Republic Commando"],
    [
        "Star Wars Empire at War Gold Pack (2006) (PROAC) (Multi)",
        "Star Wars Empire at War Gold Pack",
    ],
    ["StarCraft.II.Legacy.of.the.Void-RELOADED", "StarCraft II Legacy of the Void"],
    [
        "Strategic_Command_WWII_War_in_Europe_v1.21.01-Razor1911",
        "Strategic Command WWII War in Europe",
    ],
    ["Stronghold 2 - Deluxe", "Stronghold 2 - Deluxe"],
    ["Subnautica.v67835", "Subnautica"],
    ["Suicide.Guy.Deluxe.Edition-PLAZA", "Suicide Guy Deluxe Edition"],
    ["Super High Ball [FitGirl Repack]", "Super High Ball"],
    ["Super.Magbot.Deluxe.Edition-DARKSiDERS", "Super Magbot Deluxe Edition"],
    ["Supraland.v1.22.8", "Supraland"],
    [
        "SYNTHETIK_Legion_Rising_ULTIMATE_v39-Razor1911",
        "SYNTHETIK Legion Rising ULTIMATE",
    ],
    [
        "The Elder Scrolls - Skyrim - Special Edition [FitGirl Repack]",
        "The Elder Scrolls - Skyrim - Special Edition",
    ],
    [
        "The Legend of Zelda - Breath of the Wild [FitGirl Repack]",
        "The Legend of Zelda - Breath of the Wild",
    ],
    [
        "The Legend of Zelda Twilight Princess HD (EUR)",
        "The Legend of Zelda Twilight Princess HD",
    ],
    ["The Pathless [FitGirl Repack]", "The Pathless"],
    ["The Wonderful 101 Remastered [FitGirl Repack]", "The Wonderful 101 Remastered"],
    ["The.Beginners.Guide.(2015).REPACK-KaOs", "The Beginners Guide"],
    ["The.Companion-CODEX", "The Companion"],
    [
        "The.Outer.Worlds.Murder.On.Eridanos.v1.5.1.712.REPACK-KaOs",
        "The Outer Worlds Murder On Eridanos",
    ],
    ["The.Stanley.Parable.REPACK-KaOs", "The Stanley Parable"],
    ["Timelie v.1.1.0 [GOG] (2020)", "Timelie"],
    ["Titanfall 2 [FitGirl Repack]", "Titanfall 2"],
    ["Total War - WARHAMMER II [FitGirl Repack]", "Total War - WARHAMMER II"],
    ["Turnip.Boy.Commits.Tax.Evasion-GOG", "Turnip Boy Commits Tax Evasion"],
    ["Unlocked-DOGE", "Unlocked"],
    ["Vampirem-PLAZA", "Vampirem"],
    ["Viscera Cleanup Detail [FitGirl Repack]", "Viscera Cleanup Detail"],
    [
        "Warhammer 40000 Dawn of War II Master Collection - ELAMIGOS",
        "Warhammer 40000 Dawn of War II Master Collection",
    ],
    [
        "Warhammer 40K Dawn of War Soulstorm [PC-Ver1.20]",
        "Warhammer 40K Dawn of War Soulstorm",
    ],
    ["Wheelchair.Simulator.VR-VREX", "Wheelchair Simulator VR"],
    ["Wobbledogs.Early.Access", "Wobbledogs"],
    ["X3 - Terran War Pack [FitGirl Repack]", "X3 - Terran War Pack"],
    ["Yakuza 0 (Update 2 + Digital Content) -[DODI Repack]", "Yakuza 0"],
    ["Yakuza Kiwami 2 [FitGirl Repack]", "Yakuza Kiwami 2"],
    ["Yakuza Kiwami [FitGirl Repack]", "Yakuza Kiwami"],
    ["Yakuza Like a Dragon - [DODI Repack]", "Yakuza Like a Dragon"],
    [
        "[ELECTRO-TORRENT.PL]Guacamelee! Super Turbo Championship Edition-GOG",
        "Guacamelee! Super Turbo Championship Edition",
    ],
]

fileExamples = [
    ["1001.Spikes.rar", "1001 Spikes"],
    ["Argus.Panoptes.rar", "Argus Panoptes"],
    ["Art.of.rally.v1.3.1a.rar", "Art of rally"],
    ["ASTRONEER.v1.21.127.0.rar", "ASTRONEER"],
    ["Axiom.Verge.2.v1.0.20.rar", "Axiom Verge 2"],
    ["Beat.Blast.rar", "Beat Blast"],
    ["Before.We.Leave.v1.0301.rar", "Before We Leave"],
    ["Death.Trash.v0.7.14.rar", "Death Trash"],
    ["Delphyq.Early.Access.rar", "Delphyq"],
    ["Diner.Bros.Inc-DARKZER0.rar", "Diner Bros Inc"],
    ["Dorfromantik.v0.2.0.2.rar", "Dorfromantik"],
    [
        "ENDER.LILIES.Quietus.of.the.Knights.v1.1.2.rar",
        "ENDER LILIES Quietus of the Knights",
    ],
    [
        "EVERSPACE.2.Zharkov.The.Vortex.Early.Access.zip",
        "EVERSPACE 2 Zharkov The Vortex",
    ],
    [
        "Fallen.Enchantress.Legendary.Heroes.v3.0.rar",
        "Fallen Enchantress Legendary Heroes",
    ],
    ["Flynn.Son.of.Crimson-GOG.rar", "Flynn Son of Crimson"],
    ["GAME.exe.rar", "GAME"],
    ["Going.Medieval.v0.5.31.15.rar", "Going Medieval"],
    ["GTTOD.Get.To.The.Orange.Door.rar", "GTTOD Get To The Orange Door"],
    ["Hardspace.Shipbreaker.v0.6.0.rar", "Hardspace Shipbreaker"],
    ["Heros.Hour.v1.5.8.rar", "Heros Hour"],
    ["Jazzpunk.Directors.Cut.tar.zst", "Jazzpunk Directors Cut tar"],
    ["LASER.CHESS.Deflection.rar", "LASER CHESS Deflection"],
    ["Minoria.v1.085c.rar", "Minoria"],
    [
        "Mount.and.Blade.II.Bannerlord.e1.6.1.Hotfix.zip",
        "Mount and Blade II Bannerlord",
    ],
    ["My.Time.At.Portia.v11.09.2021.zip", "My Time At Portia"],
    ["No.Place.Like.Home.v0.17.134.rar", "No Place Like Home"],
    ["Old.World.v1.0.5463.rar", "Old World"],
    ["Olija.v2.1.2021.rar", "Olija"],
    ["Opus.Magnum.v29.08.2021.rar", "Opus Magnum"],
    ["Oxygen.Not.Included.v479045.rar", "Oxygen Not Included"],
    ["Patron.v1.009.2.rar", "Patron"],
    ["Phasmophobia.v0.3.0.5.zip", "Phasmophobia"],
    ["Planet.Centauri.v0.12.1b.rar", "Planet Centauri"],
    ["Poly.Bridge.2.v1.29.rar", "Poly Bridge 2"],
    ["Power.of.Ten.Build 7121697.rar", "Power of Ten"],
    ["PSYCRON.rar", "PSYCRON"],
    ["Rebel.Inc.Escalation.v0.11.0.6.rar", "Rebel Inc Escalation"],
    ["Residual.rar", "Residual"],
    ["Residual.v1.1.2.rar", "Residual"],
    ["Revita.v0.7.1f.rar", "Revita"],
    ["REVO.rar", "REVO"],
    ["Star.Dynasties.v1.0.0.4.rar", "Star Dynasties"],
    ["Starmancer.v0.1.45.rar", "Starmancer"],
    ["Subnautica.Below.Zero.v45588.zip", "Subnautica Below Zero"],
    ["Subnautica.v68382.rar", "Subnautica"],
    ["Suit.for.Hire.v06.09.2021.rar", "Suit for Hire"],
    ["T.Minus.30.rar", "T Minus"],
    ["Voidtrain.v6849.zip", "Voidtrain"],
    ["Hell.is.Other.Demons.Build.6901054.rar", "Hell is Other Demons"],
    ["ICBM.v1.01.00.rar", "ICBM"],
    ["Infinifactory.v1.0a-GOG.rar", "Infinifactory"],
    [
        "Legend.of.Keepers.Career.of.a.Dungeon Manager.v1.0.5.rar",
        "Legend of Keepers Career of a Dungeon Manager",
    ],
    ["Loopindex.rar", "Loopindex"],
    ["Megaquarium.v2.2.4g.rar", "Megaquarium"],
    ["Mindustry.Build.126.2.rar", "Mindustry 2"],
    ["MOLEK.SYNTEZ.v1.13.rar", "MOLEK SYNTEZ"],
    [
        "Niche.A.Genetics.Survival.Game.v25.06.2021.rar",
        "Niche A Genetics Survival Game",
    ],
    ["NITE.Team.4.v23.06.2021.rar", "NITE Team 4"],
    ["Noita.v12.03.2021.rar", "Noita"],
    ["Nova.Drift.Build.6568309.rar", "Nova Drift"],
    ["Nuclear.Throne.v06.11.2017.rar", "Nuclear Throne"],
    ["Outer.Wilds.v1.0.7.rar", "Outer Wilds"],
    ["OUTRIDERS-0xdeadc0de (Inc. ONLINE-FIX) RePack [FULL GAME].iso", "OUTRIDERS"],
    ["Parkitect.v1.7t3.rar", "Parkitect"],
    [
        "POSTAL.4.No.Regerts.Thursday.Early.Access.zip",
        "POSTAL 4 No Regerts Thursday",
    ],  # XXX NOTE that this one still isn't right - but I don't want to start stripping off weekdays from everything so it stays
    ["Prison.Architect.v19.06.2021.rar", "Prison Architect"],
    ["Rail.Route.Early.Access.rar", "Rail Route"],
    ["Rain.On.Your.Parade.rar", "Rain On Your Parade"],
    ["Rogue.Heroes.Ruins.of.Tasos.v2.0.rar", "Rogue Heroes Ruins of Tasos"],
    ["Rogue.Legacy.2.v29.06.2021.rar", "Rogue Legacy 2"],
    ["ROUNDS.rar", "ROUNDS"],
    ["Serin.Fate.v0.5.4.9.rar", "Serin Fate"],
    ["Space.Haven.v0.12.6.rar", "Space Haven"],
    ["SpaceChem.v1015.rar", "SpaceChem"],
    ["SPROUT.Build.6632648.rar", "SPROUT"],
    ["Star.Renegades.v1.4.0.5.rar", "Star Renegades"],
    ["StarDrive.2.v1.5h.rar", "StarDrive 2"],
    ["Startup.Company.v1.24.rar", "Startup Company"],
    ["Struggling.v1.0.4.rar", "Struggling"],
    ["Sunblaze.v21.06.2021.rar", "Sunblaze"],
    ["Surviving.the.Aftermath.v1.16.0.9362.rar", "Surviving the Aftermath"],
    ["The.Citadel.v22.06.2021.rar", "The Citadel"],
    ["The.Slormancer.v0.2.03.rar", "The Slormancer"],
    ["The.Unexpected.Quest.rar", "The Unexpected Quest"],
    ["Wayward.Beta.2.10.7.rar", "Wayward"],
    ["Zoo.Tycoon.2.Ultimate.Collection.zip", "Zoo Tycoon 2 Ultimate Collection"],
    ["ELDERBORN.v1.037.rar", "ELDERBORN"],
    ["GRIME.v1.0.4.5.rar", "GRIME"],
    ["HighFleet.v11.08.2021.rar", "HighFleet"],
    ["INVERT.rar", "INVERT"],
    ["Spelunky.2.v1.23.2.rar", "Spelunky 2"],
    ["Stationeers.v0.2.2943.14662.rar", "Stationeers"],
    ["Straimium.Immortaly.Build.6304372.rar", "Straimium Immortaly"],
    ["Terraforming.Mars.v1.3000.rar", "Terraforming Mars"],
    ["TerraTech.v1.4.10.3.rar", "TerraTech"],
    ["The.Last.Spell.v0.92.2.3.rar", "The Last Spell"],
    ["Voxel.Tycoon.v0.86.1.rar", "Voxel Tycoon"],
    ["Warpips.v1.4.rar", "Warpips"],
    ["Wildermyth.v1.0.325.rar", "Wildermyth"],
    ["Wire.Lips.v1.11.rar", "Wire Lips"],
    ["Wirewalk.rar", "Wirewalk"],
    ["30XX.v0.21.2.rar", "30XX"],
    [
        "5D.Chess.With.Multiverse.Time.Travel.v28.10.2020.rar",
        "5D Chess With Multiverse Time Travel",
    ],
    [
        "8Doors.Arums.Afterlife.Adventure.Build.6891335.rar",
        "8Doors Arums Afterlife Adventure",
    ],
    ["A.Little.Golf.Journey.v0.0.115.rar", "A Little Golf Journey"],
    ["A.Monsters.Expedition.v09.08.2021.rar", "A Monsters Expedition"],
    ["A.Short.Hike.v1.9.3.rar", "A Short Hike"],
    [
        "A.Tale.of.Synapse.The.Chaos.Theories.v23.07.2021.rar",
        "A Tale of Synapse The Chaos Theories",
    ],
    ["Age.of.Darkness.Final.Stand.v0.1.5.rar", "Age of Darkness Final Stand"],
    ["AI.War.2.v3.307.rar", "AI War 2"],
    ["Airborne.Kingdom.v1.0.1.rar", "Airborne Kingdom"],
    ["Airmen.v18.07.2021.rar", "Airmen"],
    ["Airships.Conquer.the.Skies.v1.0.21.4.rar", "Airships Conquer the Skies"],
    ["Astrox.Imperium.v0.0121.rar", "Astrox Imperium"],
    ["Atrio.The.Dark.Wild.rar", "Atrio The Dark Wild"],
    ["Avorion.v2.0.6.rar", "Avorion"],
    ["Axiom.Verge.v1.41.rar", "Axiom Verge"],
    ["Baba.Is.You.rar", "Baba Is You"],
    ["Banished.v1.0.7.Build.170910.rar", "Banished"],
    ["Bastion.v1.50436.rar", "Bastion"],
    [
        "Batbarian.Testament.of.the.Primordials.v1.2.1.rar",
        "Batbarian Testament of the Primordials",
    ],
    ["Beard.Blade.rar", "Beard Blade"],
    ["Beat.Hazard.2.v1.16.rar", "Beat Hazard 2"],
    ["Bloons.TD.6.v27.0.4218.rar", "Bloons TD 6"],
    ["Breakwaters.v0.1.59.rar", "Breakwaters"],
    ["Brick.Rigs.v16.07.2021.rar", "Brick Rigs"],
    [
        "Bug.Fables.The.Everlasting.Sapling.v1.1.rar",
        "Bug Fables The Everlasting Sapling",
    ],
    ["Carcassonne.Tiles.&.Tactics.v1.10.2967.2.rar", "Carcassonne Tiles & Tactics"],
    ["Carrier.Command.2.rar", "Carrier Command 2"],
    ["Cartel.Tycoon.v0.9.0.1660.rar", "Cartel Tycoon"],
    ["Castlevania.Advance.Collection.rar", "Castlevania Advance Collection"],
    ["Caves.of.Qud.v2.0.202.97.rar", "Caves of Qud"],
    ["Chernobylite.Final.Stage.Early.Access.rar", "Chernobylite Final Stage"],
    ["Clan.N.v23.07.2021.rar", "Clan N"],
    ["Colony.Survival.v0.8.1.8.rar", "Colony Survival"],
    ["Craftopia.v20210715.1741.rar", "Craftopia"],
    ["Crea.v1.7.6.rar", "Crea"],
    ["Crumble.Build.6163855.rar", "Crumble"],
    ["Crusader.Kings.III.v1.4.2.rar", "Crusader Kings III"],
    ["Cyber.Defense.rar", "Cyber Defense"],
    ["Dark.Light.v26.07.2021.rar", "Dark Light"],
    ["Darkest Dungeon 2.rar", "Darkest Dungeon 2"],
    ["Dead.Estate.v1.1.2.rar", "Dead Estate"],
    ["Deaths.Gambit.Afterlife.v1.1.5.FIXED.rar", "Deaths Gambit Afterlife"],
    ["Delver.v1.07.rar", "Delver"],
    ["Despots.Game.v0.15.0.3.rar", "Despots Game"],
    [
        "Dininho.Adventures.Definitive.Edition.Build.6922959.rar",
        "Dininho Adventures Definitive Edition",
    ],
    ["Dread.Templar.Early.Access.rar", "Dread Templar"],
    ["Dream.Engines.Nomad.Cities.v0.5.259.rar", "Dream Engines Nomad Cities"],
    ["Dredgers.v44.rar", "Dredgers"],
    ["Duck.Game.v1.5.rar", "Duck Game"],
    ["Dungeon.Keeper.2.rar", "Dungeon Keeper 2"],
    ["Dungeonmans.v1.10f.rar", "Dungeonmans"],
    ["Dungeons.of.Edera.October.Early.Access.rar", "Dungeons of Edera October"],
    ["Dungreed.v13.08.2021.rar", "Dungreed"],
    ["Eastward.v1.1.0b.rar", "Eastward"],
    ["Edge.Of.Galaxy.rar", "Edge Of Galaxy"],
    ["Eggcelerate.rar", "Eggcelerate"],
    ["Embark.v0.810.rar", "Embark"],
    ["Empires.of.the.Undergrowth.v0.23001.rar", "Empires of the Undergrowth"],
    ["Endless.Legend.v1.8.52.rar", "Endless Legend"],
    ["Enter.the.Gungeon.v2.1.9.rar", "Enter the Gungeon"],
    ["Estranged.The.Departure.Build.6786590.rar", "Estranged The Departure"],
    ["Factory.Town.rar", "Factory Town"],
    ["Factory.Town.v1.5.2.rar", "Factory Town"],
    ["Factory.Town.v1.7.3.rar", "Factory Town"],
    ["Fates.of.Ort.v1.3.0.rar", "Fates of Ort"],
    ["Final.Upgrade.v0.2.47.rar", "Final Upgrade"],
    ["Flynn.Son.of.Crimson.v1.1.rar", "Flynn Son of Crimson"],
    ["Forager.v5.0.0.rar", "Forager"],
    ["Force.of.Nature.2.v1.0.21.rar", "Force of Nature 2"],
    ["Fort.Triumph.v1.1.7.rar", "Fort Triumph"],
    ["Foundation.v1.8.0.8.1118.rar", "Foundation"],
    ["Fury.Unleashed.v1.8.2.rar", "Fury Unleashed"],
    ["Future.Tanks.Area.rar", "Future Tanks Area"],
    ["Garfield.Kart.Furious.Racing.tar.zst", "Garfield Kart Furious Racing tar"],
    ["Garlic.rar", "Garlic"],
    ["Gedonia.v0.33b.rar", "Gedonia"],
    ["Get.Packed.Fully.Loaded.rar", "Get Packed Fully Loaded"],
    [
        "Getting.Over.It.with.Bennett.Foddy.v1.5762.rar",
        "Getting Over It with Bennett Foddy",
    ],
    ["GolfTopia.v20.07.2021.rar", "GolfTopia"],
    ["GoNNER+2.tar.zst", "GoNNER+2 tar"],
    ["Goop.Loop.rar", "Goop Loop"],
    ["Grow.Song.of.the.Evertree.v03.12.2021.rar", "Grow Song of the Evertree"],
    ["Guild.of.Darksteel.GOG.rar", "Guild of Darksteel GOG"],
    ["Half.Wing.rar", "Half Wing"],
    ["Haunt.Chaser.Early.Access.zip", "Haunt Chaser"],
    ["Hell.Architect.v1.0.18.rar", "Hell Architect"],
    ["HighFleet.v1.14.rar", "HighFleet"],
    ["Hydroneer.v1.7.rar", "Hydroneer"],
    [
        "Hyrule Warriors Age of Calamity (XCI).7z",
        "Hyrule Warriors Age of Calamity (XCI)",
    ],
    ["Imagine.Earth.v1.2.3.rar", "Imagine Earth"],
    ["Imagine.Earth.v1.4.2.rar", "Imagine Earth"],
    ["Industries.of.Titan.v0.18.4.rar", "Industries of Titan"],
    ["InfraSpace.v7.3.132.rar", "InfraSpace"],
    ["Interstellar.Space.Genesis.v1.3.4.rar", "Interstellar Space Genesis"],
    ["Intravenous.v1.1.6.rar", "Intravenous"],
    ["Intravenous.v1.2.16.rar", "Intravenous"],
    ["It.Lurks.Below.v1.01.62.rar", "It Lurks Below"],
    ["Kainga.Seeds.of.Civilization.Early.Access.rar", "Kainga Seeds of Civilization"],
    ["Kingdoms.Reborn.v0.54.rar", "Kingdoms Reborn"],
    ["KingSim.rar", "KingSim"],
    ["Kubifaktorium.v24.11.2021.rar", "Kubifaktorium"],
    ["Kubifaktorium.v6.12.2021.rar", "Kubifaktorium"],
    ["Lens.Island.v26.11.2021.rar", "Lens Island"],
    ["Logic.World.v0.90.3.rar", "Logic World"],
    ["Lonely.Mountains.Downhill.v20.07.2021.rar", "Lonely Mountains Downhill"],
    ["Loop.Hero.rar", "Loop Hero"],
    ["Mad.Games.Tycoon.2.v2021.07.22A.rar", "Mad Games Tycoon 2"],
    ["Mashinky.v0.60.181.rar", "Mashinky"],
    ["Master.of.Magic.v1.3.1.rar", "Master of Magic"],
    ["Melvor.Idle.v1.0.rar", "Melvor Idle"],
    ["Mercury.Fallen.v30.4.rar", "Mercury Fallen"],
    ["Milli.and.Greg.rar", "Milli and Greg"],
    ["Mini.Metro.Creative.Mode.rar", "Mini Metro Creative Mode"],
    ["Mini.Metro.Release.49.rar", "Mini Metro Release"],
    ["MMORPG.Tycoon.2.v0.18.0.rar", "MMORPG Tycoon 2"],
    ["MMORPG.Tycoon.2.v0.18.17.rar", "MMORPG Tycoon 2"],
    ["Nebuchadnezzar.v1.2.4.rar", "Nebuchadnezzar"],
    ["Neon.Abyss.v1.4.4.rar", "Neon Abyss"],
    ["Neon.Abyss.v1.4.5.rar", "Neon Abyss"],
    ["Neon.Chrome.v1.1.7.rar", "Neon Chrome"],
    [
        "Nimbatus.The.Space.Drone.Constructor.v1.1.4.rar",
        "Nimbatus The Space Drone Constructor",
    ],
    ["NMNE.rar", "NMNE"],
    ["Nuclear.Blaze.v1.0.3.rar", "Nuclear Blaze"],
    ["Old.World.v1.0.56149.rar", "Old World"],
    [
        "Orbital.Bullet.The.360.Rogue.lite.v0.2.3.rar",
        "Orbital Bullet The 360 Rogue lite",
    ],
    ["Order.of.Battle.World.War.II.v9.0.3.rar", "Order of Battle World War II"],
    ["Oxenfree.v3.1.0.rar", "Oxenfree"],
    ["People.Playground.v1.22.rar", "People Playground"],
    ["Phantom.Brigade.v0.13.0.rar", "Phantom Brigade"],
    ["PICO.PARK.rar", "PICO PARK"],
    ["Post.Void.v1.1.0b.rar", "Post Void"],
    [
        "Potion.Craft.Alchemist.Simulator.Early.Access.rar",
        "Potion Craft Alchemist Simulator",
    ],
    ["Project.Downfall.v0.9.22.0.rar", "Project Downfall"],
    ["Project.Hospital.v1.2.22362.rar", "Project Hospital"],
    ["Project.Warlock.v1.0.4.6.rar", "Project Warlock"],
    ["Quake.II.RTX-GOG.rar", "Quake II RTX"],
    [
        "Ragnorium.Episode.31.I.Build.My.Colony.Early.Access.rar",
        "Ragnorium Episode 31 I Build My Colony",
    ],
    ["Ravensword.Undaunted.v0.2.1.HotFix.rar", "Ravensword Undaunted"],
    ["Re.Surs.rar", "Re Surs"],
    ["Realms.of.Magic.v0.22.0.rar", "Realms of Magic"],
    [
        "Record.of.Lodoss.War.Deedlit.in.Wonder.Labyrinth.v1.1.1.8.rar",
        "Record of Lodoss War Deedlit in Wonder Labyrinth",
    ],
    ["REPLIKATOR.Early.Access.rar", "REPLIKATOR"],
    ["Rift.Wizard.rar", "Rift Wizard"],
    ["RimWorld.v1.3.3171.rar", "RimWorld"],
    ["Rise.to.Ruins-GOG.zip", "Rise to Ruins"],
    ["Rogues.Tale.v2.11.rar", "Rogues Tale"],
    ["Ruinarch.v0.7.rar", "Ruinarch"],
    ["Samurai.Gunn.2.rar", "Samurai Gunn 2"],
    ["SATORI.rar", "SATORI"],
    ["Seed.of.Life.v1.0.4.rar", "Seed of Life"],
    ["Selfless.Heroes.rar", "Selfless Heroes"],
    ["shapez.io.v1.4.4.rar", "shapez io"],
    ["Siege.Survival.Gloria.Victis.v6998499.zip", "Siege Survival Gloria Victis"],
    ["simmiland.v1.4.15.rar", "simmiland"],
    ["Sir.Lovelot.rar", "Sir Lovelot"],
    ["Skid.Cities.rar", "Skid Cities"],
    ["Slipways.v1.1-777.rar", "Slipways"],
    ["Songs.of.Syx.v0.58.35b.rar", "Songs of Syx"],
    [
        "Sonic.and.All.Stars.Racing.Transformed.Collection.rar",
        "Sonic and All Stars Racing Transformed Collection",
    ],
    ["Space.Engineers.v1.199.020.zip", "Space Engineers"],
    ["Star.Valor.v1.3.1.rar", "Star Valor"],
    ["Stardew.Valley.v1.5.4.Hotfix.rar", "Stardew Valley"],
    ["Steel.Assault.Build.7670582.rar", "Steel Assault"],
    ["Stephens.Sausage.Roll.tar.zst", "Stephens Sausage Roll tar"],
    ["Stormworks.Buil.and.Rescue.v1.2.12.rar", "Stormworks Buil and Rescue"],
    ["Superfighters.Deluxe.v1.3.7d.rar", "Superfighters Deluxe"],
    ["Surgeon.Simulator.2.rar", "Surgeon Simulator 2"],
    ["Sword.of.the.Necromancer.v2.1.0.rar", "Sword of the Necromancer"],
    ["Tales.of.Majeyal.v1.7.4.ALL.DLC.GOG.rar", "Tales of Majeyal"],
    ["Teardown.v0.9.0.rar", "Teardown"],
    ["That.Flipping.Mountain.rar", "That Flipping Mountain"],
    [
        "The Legend of Zelda Skyward Sword HD.nsp",
        "The Legend of Zelda Skyward Sword HD",
    ],
    ["The.Battle.of.Polytopia.v2.0.58.rar", "The Battle of Polytopia"],
    ["The.Binding.of.Isaac.Repentance.v1.7.7.rar", "The Binding of Isaac Repentance"],
    ["The.Colonists.v1.5.14.2.rar", "The Colonists"],
    ["THE.CORRIDOR.rar", "THE CORRIDOR"],
    ["The.Immortal.Mayor.rar", "The Immortal Mayor"],
    ["The.Riftbreaker.Build.6932326.zip", "The Riftbreaker"],
    ["The.Signal.State.rar", "The Signal State"],
    ["The.Universim.v0.1.51.rar", "The Universim"],
    ["TheoTown.v04.09.2021.rar", "TheoTown"],
    ["TheoTown.v1.10.13.rar", "TheoTown"],
    ["They.Are.Billions.v1.1.13.rar", "They Are Billions"],
    ["Tile.Miner.rar", "Tile Miner"],
    ["Timberborn.v27.09.2021.rar", "Timberborn"],
    ["Timberborn.v30.11.2021.rar", "Timberborn"],
    ["Tinkertown.v0.8.1.rar", "Tinkertown"],
    ["Transport.INC.v1.3.5.rar", "Transport INC"],
    ["Trashed.v0.55.rar", "Trashed"],
    ["Travellers.Rest.v0.4.3.1f.rar", "Travellers Rest"],
    [
        "TROUBLESHOOTER.Abandoned.Children.v09.08.2021.zip",
        "TROUBLESHOOTER Abandoned Children",
    ],
    ["Turmoil.v3.0.38a.rar", "Turmoil"],
    ["uFactory.v0.6.5.3.rar", "uFactory"],
    ["Ultimate.ADOM.Caverns.of.Chaos.v1.0.0.2.rar", "Ultimate ADOM Caverns of Chaos"],
    ["ULTRAKILL.Build.6928744.rar", "ULTRAKILL"],
    ["Unbound.Worlds.Apart.v1.0.3.rar", "Unbound Worlds Apart"],
    ["UnderMine.v1.2.1.14.rar", "UnderMine"],
    ["Undungeon.v1.0.5.rar", "Undungeon"],
    ["Universe.Sandbox.2.v27.2.1.rar", "Universe Sandbox 2"],
    ["Universe.Sandbox.2.v28.2.0.rar", "Universe Sandbox 2"],
    ["Unrailed.v25.07.2021.rar", "Unrailed"],
    ["UNSIGHTED.rar", "UNSIGHTED"],
    ["Unsouled.Early.Access.rar", "Unsouled"],
    ["Usurper.Soulbound.Early.Access.rar", "Usurper Soulbound"],
    ["Valheim.v0.204.4.rar", "Valheim"],
    ["Valheim.v0.205.5.rar", "Valheim"],
    ["Vandozer.rar", "Vandozer"],
    ["Voidigo.rar", "Voidigo"],
    ["Volcanoids.v1.25.338.0.rar", "Volcanoids"],
    ["Vomitoreum.v02.08.2021.rar", "Vomitoreum"],
    ["Voxel.Tycoon.v0.87.rar", "Voxel Tycoon"],
    ["VVVVVV.v2.3.3.rar", "VVVVVV"],
    ["Wandersong.rar", "Wandersong"],
    ["Whos.Your.Daddy.v04.09.2021.rar", "Whos Your Daddy"],
    ["Xenias.Ark.v1.0.1.rar", "Xenias Ark"],
    ["Ziggurat.2.v01.12.2021.rar", "Ziggurat 2"],
    ["Anew.The.Distant.Light.Early.Access.rar", "Anew The Distant Light"],
    ["Arietta.of.Spirits.rar", "Arietta of Spirits"],
    ["BAD.END.THEATER.rar", "BAD END THEATER"],
    ["Big.NEON.Tower.VS.Tiny.Square.rar", "Big NEON Tower VS Tiny Square"],
    ["Blaster.Master.Zero.3.rar", "Blaster Master Zero 3"],
    ["Bomb.Chicken.rar", "Bomb Chicken"],
    ["Celeste.v1.4.0.0.rar", "Celeste"],
    ["Cyber.Shadow.v1.04.rar", "Cyber Shadow"],
    ["Drunken.Dad.Simulator.rar", "Drunken Dad Simulator"],
    ["Galactic.Mining.Corp.Build.7148823.rar", "Galactic Mining Corp"],
    ["Glyph.Build.7166458.rar", "Glyph"],
    ["Goats.Tale.Early.Access.rar", "Goats Tale"],
    [
        "Hundred.Days.Winemaking.Simulator.v1.1.3w1.rar",
        "Hundred Days Winemaking Simulator",
    ],
    ["Mini.Motorways.v10.08.2021.rar", "Mini Motorways"],
    ["PixARK.v1.134.rar", "PixARK"],
    ["Rise.of.Industry.v2.3.2.rar", "Rise of Industry"],
    ["Rising.Hell.v1.1.4.rar", "Rising Hell"],
    ["SimCasino.v18.06.2021.rar", "SimCasino"],
    ["SNKRX.v26.07.2021.rar", "SNKRX"],
    ["Stand.By.Me.v1.1.3.rar", "Stand By Me"],
    ["Stardew.Valley.v1.5.5.Beta.rar", "Stardew Valley"],
    ["Sunshine.Heavy.Industries.rar", "Sunshine Heavy Industries"],
    ["Super.Chicken.Jumper.rar", "Super Chicken Jumper"],
    ["Super.Worldbox.v0.9.6.rar", "Super Worldbox"],
    ["Train.Valley.2.Build.197.rar", "Train Valley 2"],
    ["Vagante.v1.10.rar", "Vagante"],
    ["Webbed.v1.03b.rar", "Webbed"],
    ["Wizard.of.Legend.Phantom.rar", "Wizard of Legend Phantom"],
    ["60.Parsecs.v1.3.2.rar", "60 Parsecs"],
    ["A.Short.Hike.v1.8.14.rar", "A Short Hike"],
    ["ADOM.Ancient.Domains.Of.Mystery.v3.3.4.1.rar", "ADOM Ancient Domains Of Mystery"],
    ["Almighty.Kill.Your.Gods.Early.Access.zip", "Almighty Kill Your Gods"],
    ["Amnesia.The.Dark.Descent.v02.10.2018.rar", "Amnesia The Dark Descent"],
    ["Another.Brick.in.the.Mall.v1.1.4.rar", "Another Brick in the Mall"],
    ["Ape.Out.rar", "Ape Out"],
    ["Astalon.Tears.of.the.Earth.v1.0.11.rar", "Astalon Tears of the Earth"],
    ["Autonauts.v137.14.11.rar", "Autonauts"],
    ["Bamerang.rar", "Bamerang"],
    [
        "Barotrauma.Thunder.Under.The.Ice.Early.Access.rar",
        "Barotrauma Thunder Under The Ice",
    ],
    ["Battle.Axe.rar", "Battle Axe"],
    ["BlackChain.v1.0.7.rar", "BlackChain"],
    ["Blaster.Master.Zero.2.v16.06.2021.rar", "Blaster Master Zero 2"],
    ["Blaster.Master.Zero.v16.06.2021.rar", "Blaster Master Zero"],
    ["Boppio.v0.3.0.rar", "Boppio"],
    ["Broken.Universe.Tower.Defense.Early.Access.rar", "Broken Universe Tower Defense"],
    ["Bugsnax.v1.06.58006.rar", "Bugsnax"],
    ["City.Game.Studio.v1.0.rar", "City Game Studio"],
    ["Cloud.Gardens.v0.13.8.rar", "Cloud Gardens"],
    ["Craft.The.World.v1.9.002.rar", "Craft The World"],
    ["Crosscode.1.4.1-4.GOG.rar", "Crosscode"],
    ["Curse.of.the.Dead.Gods.v1.24.4.rar", "Curse of the Dead Gods"],
    ["Distant.Kingdoms.v11519.rar", "Distant Kingdoms"],
    ["Dobo's.Heroes.rar", "Dobo's Heroes"],
    ["Dragon.Quest.Builders.2.v20210428.rar", "Dragon Quest Builders 2"],
    [
        "Eador.Masters.of.the.Broken.World.v1.8.3.rar",
        "Eador Masters of the Broken World",
    ],
    ["Eco.v0.9.3.5.rar", "Eco"],
    ["Empyrion.Galactic.Survival.v1.5.1.zip", "Empyrion Galactic Survival"],
    ["Endzone.A.World.Apart.v1.0.7822.rar", "Endzone A World Apart"],
    ["Environmental.Station.Alpha.v06.02.2020.rar", "Environmental Station Alpha"],
    ["Five.Nations.v1.0.2.rar", "Five Nations"],
    ["Flotsam.v0.4.0e4.rar", "Flotsam"],
    ["FTL.Faster.Than.Light.v1.6.14.rar", "FTL Faster Than Light"],
    ["GemCraft.Frostborn.Wrath.v1.2.1a.rar", "GemCraft Frostborn Wrath"],
    ["Geneforge.1.Mutagen.v1.0.2.1.rar", "Geneforge 1 Mutagen"],
    ["Geometry.Arena.rar", "Geometry Arena"],
    ["GetsuFumaDen.Undying.Moon.v17.06.2021.rar", "GetsuFumaDen Undying Moon"],
    ["Golden.Light.v04.06.2021.rar", "Golden Light"],
    ["Good.Company.v0.9.3.rar", "Good Company"],
    ["Green.With.Energy.rar", "Green With Energy"],
    ["Hades.v1.37996.zip", "Hades"],
    ["Hard.Reset.Redux.v1.1.3.0.zip", "Hard Reset Redux"],
    ["HROT.v0.3.1.rar", "HROT"],
    ["HUNTDOWN.v13.05.2021.rar", "HUNTDOWN"],
    ["Hyper.Light.Drifter.Update.36.rar", "Hyper Light Drifter Update"],
    ["Hyper.Light.Drifter.v17.10.2018.rar", "Hyper Light Drifter"],
    ["Infinitode.2.rar", "Infinitode 2"],
    ["Katana.ZERO.v1.0.5.rar", "Katana ZERO"],
    ["Kenshi.v1.0.55.zip", "Kenshi"],
    ["Kingdoms.and.Castles.v117r7z.rar", "Kingdoms and Castles"],
    ["Last.Epoch.v0.8.Early.Access.zip", "Last Epoch"],
    ["Lets.Build.a.Zoo.rar", "Lets Build a Zoo"],
    ["Lewd.Girls.Leave.Me.Alone.rar", "Lewd Girls Leave Me Alone"],
    ["Lichtspeer.Double.Speer.Edition.v1.01.rar", "Lichtspeer Double Speer Edition"],
    ["Lost.Ruins.v1.0.9.rar", "Lost Ruins"],
    ["Mayhem.in.Single.Valley.v4.0.7.rar", "Mayhem in Single Valley"],
    ["Night.Delivery.v1.09.rar", "Night Delivery"],
    ["Oceans.Heart.rar", "Oceans Heart"],
    ["Orcs.Must.Die.2.Complete.zip", "Orcs Must Die 2 Complete"],
    ["Overcrowd.A.Commute.Em.Up.v1.0.41.rar", "Overcrowd A Commute Em Up"],
    ["Paleon.rar", "Paleon"],
    [
        "Panzer.Corps.2.Field.Marshal.Edition.v1.01.23.zip",
        "Panzer Corps 2 Field Marshal Edition",
    ],
    ["Patch.Quest.Early.Access.rar", "Patch Quest"],
    ["Portal.Reloaded.v1.1.0.rar", "Portal Reloaded"],
    ["Prodigal.v1.3.1.rar", "Prodigal"],
    ["Production.Line.v1.81e.rar", "Production Line"],
    ["R.Type.Dimensions.rar", "R Type Dimensions"],
    ["Radical.Relocation.v1.5.0.rar", "Radical Relocation"],
    ["Raft.Update.13.rar", "Raft"],
    ["Rain.World.v1.5.rar", "Rain World"],
    [
        "RECONNECT.The.Heart.of.Darkness.Early.Access.rar",
        "RECONNECT The Heart of Darkness",
    ],
    ["Resident Evil Village-FULL UNLOCKED RePack.iso", "Resident Evil Village"],
    ["Reventure.v1.9.5.rar", "Reventure"],
    [
        "rld-sanctum2.iso",
        "sanctum2",
    ],  # XXX NOTE this one is also not entirely correct, as there should be a space between sanctum and 2, but I'm not going to go add arbitrary spaces
    ["ScourgeBringer.v1.52.rar", "ScourgeBringer"],
    ["setup_8bit_hordes_2.0.0.3.exe", "8bit hordes"],
    ["Simonas.Requiem.Build.6668649.rar", "Simonas Requiem"],
    ["SimPocalypse.rar", "SimPocalypse"],
    ["Sky.Haven.v0.6.3.39.rar", "Sky Haven"],
    ["Slave.Princess.Sarah.rar", "Slave Princess Sarah"],
    ["Slime.Rancher.v1.4.3.rar", "Slime Rancher"],
    ["Snowtopia.Ski.Resort.Tycoon.v0.14.12.rar", "Snowtopia Ski Resort Tycoon"],
    ["Software.Inc.Alpha.11.7.55.rar", "Software Inc Alpha"],
    ["Speed.Limit.v1.2.3.rar", "Speed Limit"],
    ["Starbound.v1.4.4.rar", "Starbound"],
    ["StarSector.0.9.5a-RC15.rar", "StarSector"],
    ["Stronghold.Crusader.HD.v1.41a.rar", "Stronghold Crusader HD"],
    ["Stronghold2.Steam.Edition.v1.5.zip", "Stronghold2 Steam Edition"],
    ["Super.Bit.Blaster.XL.rar", "Super Bit Blaster XL"],
    ["Tales.of.Majeyal.v1.7.2.ALl.DLC.GOG.rar", "Tales of Majeyal"],
    ["Tangledeep.v1.4i_3.rar", "Tangledeep"],
    ["Teardown.v0.7.2.rar", "Teardown"],
    ["Terraria.v1.4.2.3.rar", "Terraria"],
    ["Tesla.vs.Lovecraft.v1.0.5.rar", "Tesla vs Lovecraft"],
    ["The.Company.Man.v5.06.2021.rar", "The Company Man"],
    ["The.Last.Spell.v0.91.3.rar", "The Last Spell"],
    ["The.Messenger.v04.10.2019.rar", "The Messenger"],
    ["The.Tenants.v0.553.rar", "The Tenants"],
    ["Time.to.Morp.rar", "Time to Morp"],
    ["TWWWR.Build.6228108.rar", "TWWWR"],
    ["Valley.of.No.Roads.rar", "Valley of No Roads"],
    [
        "Vigil.The.Longest.Night.The.Bounty.of.the.Night.rar",
        "Vigil The Longest Night The Bounty of the Night",
    ],
    ["Viscerafest.v0.9.0.5.rar", "Viscerafest"],
    ["Why.Pizza.rar", "Why Pizza"],
    ["Within.the.Blade.v1.1.0.1.rar", "Within the Blade"],
    ["Wobbledogs.Early.Access.rar", "Wobbledogs"],
    ["Wobbly.Life.v0.5.5.rar", "Wobbly Life"],
    [
        "Workers.&.Resources.Soviet.Republic.v0.8.4.21.rar",
        "Workers & Resources Soviet Republic",
    ],
    ["World.of.Contraptions.v0.34.0.rar", "World of Contraptions"],
    ["Worms.Armageddon.v3.8.1.GOG.rar", "Worms Armageddon"],
]

from Helpers.RegexPlugin import InputSanitizer

inputSanitizer = InputSanitizer()
dirTestCaseData = [
    [
        dirName,
        inputSanitizer.perform_directory_name_replacement(dirName, True),
        correctTranslation,
    ]
    for dirName, correctTranslation in dirExamples
]
fileTestCaseData = [
    [
        filename,
        inputSanitizer.perform_filename_replacement(filename),
        correctTranslation,
    ]
    for filename, correctTranslation in fileExamples
]

import unittest
from parameterized import parameterized


class TestSequence(unittest.TestCase):
    @parameterized.expand(fileTestCaseData)
    def test_file_name_translation(
        self, originalFilename: str, actualTranslation: str, correctTranslation: str
    ):
        self.assertEqual(
            actualTranslation,
            correctTranslation,
            f"expected '{actualTranslation}' to be '{correctTranslation}'. Original Filename: '{originalFilename}'",
        )

    @parameterized.expand(dirTestCaseData)
    def test_dir_name_translation(
        self, originalDirName: str, actualTranslation: str, correctTranslation: str
    ):
        self.assertEqual(
            actualTranslation,
            correctTranslation,
            f"expected '{actualTranslation}' to be '{correctTranslation}'. Original Dirname: '{originalDirName}'",
        )


if __name__ == "__main__":
    unittest.main()
