FROM node:16-alpine

RUN npx create-react-app steam-indexer-frontend

EXPOSE 3000

WORKDIR /steam-indexer-frontend

RUN npm install --save-dev @babel/plugin-proposal-private-property-in-object

RUN npm install react-tabs-redux

RUN npm install @chakra-ui/react

ENTRYPOINT [ "npm", "start" ]


# COPY steam-indexer-frontend/package.json .
# # COPY package-lock.json .

# RUN npm install

# COPY steam-indexer-frontend/src .

# RUN npm start
